<?php
namespace App\Service;

/**
 * Utility service for advanced mathematical operations required by the simulation engine.
 */
class MathUtility
{
    /**
     * @var float|null Stores the second random number generated by the Box-Muller transform.
     */
    private ?float $spareNormal = null;

    private float $randMaxInverse;
    private float $twoPi;

    public function __construct()
    {
        $this->randMaxInverse = 1.0 / mt_getrandmax();
        $this->twoPi = 2.0 * M_PI;
    }

    /**
     * Generates a random float between 0 and 1 from a uniform distribution.
     *
     * @return float
     */
    public function generateUniform(): float
    {
        return mt_rand() * $this->randMaxInverse;
    }

    /**
     * Checks if an event occurs given a specific probability [0, 1].
     *
     * @param float $probability The probability of the event occurring.
     * @return bool True if the event occurred, false otherwise.
     */
    public function checkProbability(float $probability): bool
    {
        return $this->generateUniform() < $probability;
    }

    /**
     * Generates a random number from a standard normal distribution (Gaussian).
     *
     * This method uses the Box-Muller transform to convert uniformly distributed
     * random numbers (from mt_rand) into normally distributed numbers with
     * a mean of 0 and a standard deviation of 1.
     *
     * Since Box-Muller generates two numbers at once, one is returned immediately
     * and the other is stored in $spareNormal for the next call.
     *
     * @return float A random number following a standard normal distribution.
     */
    public function generateStandardNormal(): float
    {
        if ($this->spareNormal !== null) {
            $result = $this->spareNormal;
            $this->spareNormal = null;
            return $result;
        }

        do {
            $x = $this->generateUniform();
            $y = $this->generateUniform();
        } while ($x <= 0);

        $radius = sqrt(-2 * log($x));
        $angle = $this->twoPi * $y;

        $this->spareNormal = $radius * sin($angle);
        return $radius * cos($angle);
    }

    /**
     * Calculates the next step in volatility using the Heston Stochastic Volatility Model.
     * * This method handles the correlated random walk (Wiener process) internally. 
     * It allows passing a pre-computed Z-score ($z1) if the volatility needs to be 
     * correlated with a stock's underlying price movement.
     *
     * @param float $currentVolatility  Current instantaneous volatility.
     * @param float $longTermVolatility Long-run mean volatility (Theta).
     * @param float $kappa              Rate of mean reversion for volatility.
     * @param float $volOfVol           Volatility of the volatility process (Xi).
     * @param float $rho                Correlation coefficient between price and volatility [-1, 1].
     * @param float $dt                 Time step in years.
     * @param float|null $z1            Optional pre-computed standard normal (for price correlation).
     * @param float|null $z2            Optional pre-computed standard normal.
     * * @return float The next instantaneous volatility.
     */
    public function calculateHestonVolatility(
        float $currentVolatility,
        float $longTermVolatility,
        float $kappa,
        float $volOfVol,
        float $rho,
        float $dt,
        ?float $z1 = null,
        ?float $z2 = null
    ): float {
        // Generate standard normal variables if the caller didn't provide them
        $z1 = $z1 ?? $this->generateStandardNormal();
        $z2 = $z2 ?? $this->generateStandardNormal();

        // Calculate the correlated Wiener process (w2) internally
        // This ensures the volatility moves inversely to the stock price (Leverage Effect)
        $w2 = ($rho * $z1) + (sqrt(1 - ($rho * $rho)) * $z2);

        // The Heston Variance Process
        $currentVariance = $currentVolatility * $currentVolatility;
        $longTermVariance = $longTermVolatility * $longTermVolatility;

        // Calculate the differential in variance
        $dv = $kappa * ($longTermVariance - $currentVariance) * $dt
            + $volOfVol * $currentVolatility * sqrt($dt) * $w2;

        // Ensure variance never goes negative (Full Truncation method)
        $nextVariance = max(0.000001, $currentVariance + $dv);
        
        return sqrt($nextVariance);
    }

    /**
     * Simulates the Merton Jump Diffusion process for sudden market shocks.
     * Returns the price multiplier and the raw components of the jump.
     *
     * @param float $lambda   The jump intensity (average number of jumps per year).
     * @param float $jumpMean The mean size of a jump (log-return).
     * @param float $jumpVol  The volatility of the jump size.
     * @param float $dt       The time step in years.
     * @return array{multiplier: float, shock_pct: float|null, exponent: float|null}
     */
    public function calculateJumpDiffusion(
        float $lambda, 
        float $jumpMean, 
        float $jumpVol, 
        float $dt
    ): array {
        $jumpProb = $lambda * $dt;

        // Roll the dice to see if a jump occurs this tick
        if ($this->checkProbability($jumpProb)) {
            $jumpZ = $this->generateStandardNormal();

            $jumpExponent = $jumpMean + ($jumpVol * $jumpZ);
            $jumpMultiplier = exp($jumpExponent);
            $shockPct = ($jumpMultiplier - 1.0) * 100.0;

            return [
                'multiplier' => $jumpMultiplier,
                'shock_pct'  => $shockPct,
                'exponent'   => $jumpExponent
            ];
        }

        // No jump occurred
        return [
            'multiplier' => 1.0,
            'shock_pct'  => null,
            'exponent'   => null
        ];
    }

    /**
     * Calculates the mean reversion drift (gravity) pulling a current value towards a target.
     * Uses a log-normal Ornstein-Uhlenbeck process approach.
     *
     * @param float $currentValue   The current state of the variable.
     * @param float $targetValue    The fundamental fair value or mean it is reverting to.
     * @param float $reversionSpeed How aggressively the value is pulled towards the target.
     * @return float The calculated gravity drift modifier.
     */
    public function calculateLogMeanReversion(
        float $currentValue,
        float $targetValue,
        float $reversionSpeed
    ): float {
        // Floor values to prevent log(0) or negative logs in geometric models
        $logTarget = log(max($targetValue, 0.000001));
        $logCurrent = log(max($currentValue, 0.000001));
        
        return $reversionSpeed * ($logTarget - $logCurrent);
    }

    /**
     * Calculates the next price using Geometric Brownian Motion (GBM) with correlated market drift.
     *
     * @param float $currentPrice      The current price of the stock.
     * @param float $currentVolatility The current instantaneous volatility.
     * @param float $drift             The expected return (drift) of the stock.
     * @param float $gravityDrift      The mean reversion drift pulling to fair value.
     * @param float $dt                The time step in years.
     * @param float $beta              The stock's beta (sensitivity to market movements).
     * @param float $marketVol         The volatility of the broader market.
     * @param float $marketZ           The systemic market shock Z-score.
     * @param float $w1                The idiosyncratic shock Z-score.
     * @return float The new price calculated via GBM.
     */
    public function calculateCorrelatedGBM(
        float $currentPrice,
        float $currentVolatility,
        float $drift,
        float $gravityDrift,
        float $dt,
        float $beta,
        float $marketVol,
        float $marketZ,
        float $w1
    ): float {
        $impliedRho = $beta * ($marketVol / max($currentVolatility, 0.01));
        $marketCorrelation = max(-0.99, min(0.99, $impliedRho));

        $sqrtDt = sqrt($dt);
        $systematicDrift = $currentVolatility * $marketCorrelation * $marketZ * $sqrtDt;
        $idiosyncraticDrift = $currentVolatility * sqrt(1 - ($marketCorrelation * $marketCorrelation)) * $w1 * $sqrtDt;
        $currentVariance = $currentVolatility * $currentVolatility;

        $gbmExponent = ($drift + $gravityDrift - 0.5 * $currentVariance) * $dt + $systematicDrift + $idiosyncraticDrift;

        return $currentPrice * exp($gbmExponent);
    }


    /**
     * Generates a random number from an Exponential distribution.
     */
    public function generateExponential(float $rate = 1.0): float
    {
        // Prevent log(0)
        $u = max($this->generateUniform(), 0.0000001);
        return -log($u) / $rate;
    }

    /**
     * Andersen's Quadratic-Exponential (QE) Discretization Scheme (2008).
     * Calculates the next variance state strictly positively, without bias.
     *
     * @param float $currentVar Current variance (Volatility squared).
     * @param float $theta      Long-term mean variance.
     * @param float $kappa      Reversion speed.
     * @param float $sigma      Volatility of volatility.
     * @param float $dt         Time step.
     * @return float The next strictly positive variance.
     */
    public function calculateQEVarianceStep(
        float $currentVar,
        float $theta,
        float $kappa,
        float $sigma,
        float $dt
    ): float {
        $expKappaDt = exp(-$kappa * $dt);
        
        // Calculate mean (m) and variance (s^2) of the next variance state
        $m = $theta + ($currentVar - $theta) * $expKappaDt;
        $s2 = ($currentVar * $sigma * $sigma * $expKappaDt / $kappa) * (1 - $expKappaDt) 
            + ($theta * $sigma * $sigma / (2 * $kappa)) * pow(1 - $expKappaDt, 2);

        // Psi determines whether to use Quadratic or Exponential approximation
        $psi = $m > 0 ? $s2 / ($m * $m) : 2.0;

        $nextVar = 0.0;

        if ($psi <= 1.5) {
            // Non-central chi-square approximation (Quadratic)
            $b2 = 2 / $psi - 1 + sqrt((2 / $psi) * (2 / $psi - 1));
            $a = $m / (1 + $b2);
            $Zv = $this->generateStandardNormal();
            $nextVar = $a * pow(sqrt($b2) + $Zv, 2);
        } else {
            // Exponential approximation
            $p = ($psi - 1) / ($psi + 1);
            $beta = (1 - $p) / $m;
            $U = $this->generateUniform();
            
            if ($U > $p) {
                // Prevent log(0) if U is extremely close to 1
                $U = min($U, 0.9999999);
                $nextVar = (1 / $beta) * log((1 - $p) / (1 - $U));
            } else {
                $nextVar = 0.0;
            }
        }

        // Failsafe floor
        return max($nextVar, 0.0000001);
    }

    /**
     * SVJJ Model: Correlated Price and Variance Jumps using Kou Double-Exponential.
     *
     * @param float $lambda   Jump intensity (arrivals per year).
     * @param float $pUp      Probability that a jump is upwards (e.g., 0.3 for heavy left-tail).
     * @param float $etaUp    Rate of up-jump exponential decay.
     * @param float $etaDown  Rate of down-jump exponential decay.
     * @param float $muV      Mean of the variance jump (exponentially distributed).
     * @param float $dt       Time step.
     * @return array{price_multiplier: float, var_jump: float, shock_pct: float|null}
     */
    public function calculateSVJJJumps(
        float $lambda,
        float $pUp,
        float $etaUp,
        float $etaDown,
        float $muV,
        float $dt
    ): array {
        $jumpProb = $lambda * $dt;

        if ($this->checkProbability($jumpProb)) {
            // Price Jump (Kou Double-Exponential)
            $isUpJump = $this->generateUniform() < $pUp;
            
            if ($isUpJump) {
                $jumpSize = $this->generateExponential($etaUp);
            } else {
                $jumpSize = -$this->generateExponential($etaDown);
            }

            $priceMultiplier = exp($jumpSize);
            $shockPct = ($priceMultiplier - 1.0) * 100.0;

            // Variance Jump (Contemporaneous)
            // Market crashes usually spike volatility harder than market rallies
            $varianceJumpRate = $isUpJump ? (1.0 / ($muV * 0.5)) : (1.0 / $muV);
            $varJump = $this->generateExponential($varianceJumpRate);

            return [
                'price_multiplier' => $priceMultiplier,
                'var_jump'         => $varJump,
                'shock_pct'        => $shockPct
            ];
        }

        return [
            'price_multiplier' => 1.0,
            'var_jump'         => 0.0,
            'shock_pct'        => null
        ];
    }
}