<?php
namespace App\Service;

/**
 * Utility service for advanced mathematical operations required by the simulation engine.
 */
class MathUtility
{
    /**
     * @var float|null Stores the second random number generated by the Box-Muller transform.
     */
    private ?float $spareNormal = null;

    /**
     * Generates a random number from a standard normal distribution (Gaussian).
     *
     * This method uses the Box-Muller transform to convert uniformly distributed
     * random numbers (from mt_rand) into normally distributed numbers with
     * a mean of 0 and a standard deviation of 1.
     *
     * Since Box-Muller generates two numbers at once, one is returned immediately
     * and the other is stored in $spareNormal for the next call.
     *
     * @return float A random number following a standard normal distribution.
     */
    public function generateStandardNormal(): float
    {
        if ($this->spareNormal !== null) {
            $result = $this->spareNormal;
            $this->spareNormal = null;
            return $result;
        }

        do {
            $x = mt_rand() / mt_getrandmax();
            $y = mt_rand() / mt_getrandmax();
        } while ($x <= 0);

        $radius = sqrt(-2 * log($x));
        $angle = 2 * M_PI * $y;

        $this->spareNormal = $radius * sin($angle);
        return $radius * cos($angle);
    }

}