#!/usr/bin/env php
<?php

// PreToolUse: Claude changes entities only; the user generates migrations with Doctrine (CLAUDE.md). Blocks writing or
// editing a file under migrations/, and the console commands that generate one. A Bash command must call the command
// through `console` to be blocked, so a grep or a note that only names it passes.

declare(strict_types=1);

function block(string $why): never
{
    fwrite(STDERR, $why . "\n");
    exit(2);
}

$input = json_decode((string) stream_get_contents(STDIN), true);
$tool = is_array($input) ? (string) ($input['tool_name'] ?? '') : '';
$args = is_array($input) ? (array) ($input['tool_input'] ?? []) : [];
$project = rtrim((string) (getenv('CLAUDE_PROJECT_DIR') ?: ($input['cwd'] ?? '')), '/');

$rule = 'Migrations are generated by the user with Doctrine (CLAUDE.md). Make the entity change only, and say in the report that it needs a migration.';

if (in_array($tool, ['Write', 'Edit', 'MultiEdit'], true)) {
    $path = (string) ($args['file_path'] ?? '');
    if ($project !== '' && str_starts_with($path, $project . '/migrations/')) {
        block($rule);
    }
} elseif ($tool === 'Bash') {
    $generate = '/\bconsole\b[^|;&\n"\'`]*\b(doctrine:migrations:(diff|generate|dump-schema|rollup)|make:migration)\b/';
    if (preg_match($generate, (string) ($args['command'] ?? '')) === 1) {
        block($rule);
    }
}

exit(0);
