services:
  aerie-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.frankenphp
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3 Support
    volumes:
      - ./:/app
      - ./docker/caddy/Caddyfile.frankenphp:/etc/frankenphp/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - aerie-database
      - aerie-redis
    env_file:
      - .env.dev
  
  aerie-worker:
    build: 
      context: .
      dockerfile: docker/php/Dockerfile.frankenphp
    volumes:
      - ./:/app
    depends_on:
      - aerie-database
      - aerie-redis
    command: sh -c "php bin/console messenger:setup-transports && exec php bin/console messenger:consume async -vv --memory-limit=128M --time-limit=3600"
    restart: unless-stopped
    env_file:
      - .env.dev

  aerie-scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.frankenphp
    restart: unless-stopped
    command: php bin/console messenger:consume scheduler_default -vv
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - aerie-database
      - aerie-redis
    env_file:
      - .env.dev
  
  # The Market Ticker
  aerie-ticker:
    profiles: ["live"]
    build:
      context: .
      dockerfile: docker/php/Dockerfile.frankenphp
    command: sh -c "sleep 5 && exec php bin/console app:market-ticker --env=prod --no-debug"
    restart: unless-stopped
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - aerie-redis
      - aerie-database
    env_file:
      - .env.dev

  # The WebSocket Server
  aerie-websocket:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.frankenphp
    command: php bin/websocket-server.php start
    restart: unless-stopped
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - aerie-redis
    env_file:
      - .env.dev

  aerie-database:
    image: mariadb:11.8
    restart: unless-stopped
    env_file:
      - .env.dev
    command: 
      - --innodb-buffer-pool-size=1G
      - --innodb-log-file-size=512M
      - --innodb-flush-log-at-trx-commit=2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

  aerie-redis:
    image: redis:8.6-trixie
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"

  mailer:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  aerie-selenium:
    image: selenium/standalone-chromium:latest
    shm_size: 2gb
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "7900:7900"
    depends_on:
      - aerie-app
  
volumes:
  caddy_data:
  caddy_config:
  db_data: