#!/bin/bash

# Get the current host user's ID and Group ID
USER_ID=$(id -u)
GROUP_ID=$(id -g)

# Execute the command inside the container AS your local user
docker compose exec --user "$USER_ID:$GROUP_ID" aerie-php php bin/console "$@"