<?php

declare(strict_types=1);

namespace App\Service\Model\Sector;

use App\Service\Model\BusinessModelInterface;

use App\Data\ModelParam;
use App\DTO\MacroStateDTO;
use App\DTO\SectorPhysicsResult;
use App\Entity\Stock;
use App\Service\Math\MathUtility;
use App\Service\Macro\MacroEngine;
use App\Service\Event\ShockEvent;
use App\Service\Math\FinancialConstants;

/**
 * Earnings strategy for Shadow Banks (Mortgage Finance, Non-bank lenders).
 * 
 * Financial Physics:
 * - Operates like a bank but without customer deposits.
 * - Funds its entire loan book via Wholesale Debt (Repo Markets, Commercial Paper).
 * - Highly vulnerable to credit market freezes and yield curve inversions.
 * - Evaluated on Return on Equity (ROE).
 */
class ShadowBankBusinessModel extends CommercialBankBusinessModel
{
    // --- Bank Levy ---
    /** A non-bank lender funded in the markets is outside the bank levy. */
    public const PAYS_BANK_LEVY = false;

    // --- Prudential Regulation ---
    /** A shadow bank takes no deposits and sits outside the District's bank capital requirement. */
    public const PRUDENTIALLY_REGULATED = false;

    // --- Operating Cyclicality & Demand Structure ---
    /** Elasticity of volumes and costs to the macro cycle (1.0 = one for one with the output gap). Wholesale-funded lending expands and contracts with credit conditions. */
    public const OPERATING_CYCLICALITY = 1.30;

    // --- Analyst Visibility & Error ---
    public const BASE_COVERAGE_VISIBILITY = 0.50;
    public const BASE_COVERAGE_ERROR = 0.10;
    public function getWholesaleLeverageLimit(): float { return 8.0; }
    public function getMoatSpread(): float { return 0.005; }

    // --- Portfolio & Asset Yield Architecture ---
    /**
     * A thirty-year mortgage book, priced off the long end and funded overnight. Longer than a deposit
     * bank's loan book by the whole of the difference between the two businesses, which is why a shadow
     * bank is the first thing a hiking cycle breaks.
     */
    public const ASSET_DURATION_YEARS = 8.0;

    /** Yield spread over 30Y mortgage benchmark earned on mortgage portfolio assets. */
    public const MORTGAGE_PORTFOLIO_SPREAD = 0.0225;
    /** Yield spread over base policy rate (SOFR) earned on direct lending private credit loans. */
    public const DIRECT_LENDING_PORTFOLIO_SPREAD = 0.0450;
    /** Minimum baseline operating EBIT yield generated by origination and servicing operations. */
    public const MIN_OPERATING_EBIT_YIELD = 0.015;

    // --- ROE & Target Architecture ---
    /** Target operating cash reserve ratio applied to corporate operating base. */
    public const TARGET_OPERATING_BUFFER  = 0.05;
    /** Hard ceiling on gross asset yield to prevent reverse-engineered revenue hyperinflation. */
    public const MAX_GROSS_ASSET_YIELD    = 0.50;

    // --- Credit Losses (ASC 326) ---
    /** Default mortgage share of the book (MortgageOriginationWeight), lent against homes; direct lending takes the rest as business credit. Through the cycle the blend loses ~0.55% a year at the bank segment rates. */
    public const DEFAULT_MORTGAGE_BOOK_SHARE = 0.60;
    /** Years of expected loss the allowance covers: mortgages prepay and middle-market loans mature well inside their contractual terms. */
    public const CECL_LIFETIME_HORIZON_YEARS = 3.0;

    // --- Revenue Shock Physics ---
    /** Volatility multiplier for top-line revenue shocks in non-bank lending markets. */
    public const REVENUE_VARIANCE_SCALAR = 0.20;
    /** Lifetime-loss multiplier per unit of IG spread widening on a leveraged private-credit book: +300bps lifts the reserve target ~0.30x. */
    public const CECL_RESERVE_SPREAD_SENSITIVITY = 10.0;
    /** Direct lending volume per unit of capital the regulated banks must hold beyond the District's opening requirement, the countercyclical buffer included: a bank syndicate with 1pp less Tier 1 headroom leaves 1.547pp more of a loan to nonbanks, on a 23.1% mean nonbank share (Irani, Iyer, Meisenzahl & Peydro 2021, RFS, Table 5 col. 1); the Basel III shock in their fn. 33 is six times larger. */
    public const CAPITAL_ARBITRAGE_SENSITIVITY = 6.70;
    /** Structural minimum operating cost-to-revenue ratio for non-bank lending operations. */
    public const MIN_EFFICIENCY_RATIO      = 0.45;

    // --- Private Credit & Corporate Default Physics ---
    /** Baseline investment-grade credit spread for normal shadow bank portfolio lending, the macro through-the-cycle IG spread. */
    public const CECL_BASELINE_CREDIT_SPREAD    = MacroEngine::BASE_CREDIT_SPREAD;
    /** Expansion sensitivity of direct lending origination when commercial banks tighten credit standards (SLOOS). */
    public const SLOOS_PRIVATE_CREDIT_EXPANSION = 0.30;
    /** Baseline 12-month forward recession probability; the lifetime loss estimate is struck at 1.0x here. */
    public const CECL_BASELINE_RECESSION_PROB   = 0.15;
    /** Lifetime-loss multiplier per unit of recession probability above baseline: a near-certain recession lifts the reserve target ~0.85x. */
    public const CECL_RESERVE_RECESSION_SENSITIVITY = 1.00;

    // --- Housing Starts & M2 Liquidity Transmission ---
    /** Sensitivity of non-bank purchase mortgage originations to residential housing starts. */
    public const HOUSING_STARTS_ORIGINATION_SENSITIVITY = 0.35;
    /** Sensitivity of private credit deployment and wholesale repo funding to M2 money supply growth. */
    public const M2_SHADOW_LIQUIDITY_SENSITIVITY = 0.30;

    // --- NIM Squeeze & Repo Market Freeze ---
    /** Default 30Y Treasury yield fallback when macroeconomic yield curve data is missing. */
    public const DEFAULT_30Y_YIELD_FALLBACK = 0.045;
    /** Target structural spread floor between 30Y mortgage yields and short-term repo funding. */
    public const TARGET_MORTGAGE_SPREAD     = 0.015;
    /** Linear sensitivity scalar for mild spread compression when yield curve flattens. */
    public const NIM_LINEAR_SENSITIVITY     = 1.00;
    /** Multiplier scaling systemic yield curve inversion sensitivity for shadow bank repo funding. */
    public const NIM_INVERSION_SCALAR       = 1.33;
    /** Quadratic coefficient amplifying repo funding freeze costs during extreme yield curve inversions. */
    public const NIM_QUADRATIC_COEFF        = 0.20;

    // --- Analyst Visibility & Error ---
    // Moved to getCoverageProfile() — see MarketConsensusEngine.

    /**
     * The book is the two portfolios the revenue streams earn on: mortgages, secured on homes, and direct loans to
     * middle-market firms, charged off at the bank segment rates.
     *
     * @return array{residential: float, consumer: float, commercial_real_estate: float, business: float}
     */
    protected function resolveLoanBookMix(Stock $stock): array
    {
        $params = $this->resolveModelParameters($stock, [
            ModelParam::MortgageOriginationWeight->value => self::DEFAULT_MORTGAGE_BOOK_SHARE,
            ModelParam::DirectLendingWeight->value       => 1.0 - self::DEFAULT_MORTGAGE_BOOK_SHARE,
        ]);
        $mortgage = max(0.0, (float) $params[ModelParam::MortgageOriginationWeight]);
        $total = $mortgage + max(0.0, (float) $params[ModelParam::DirectLendingWeight]);

        return self::completeLoanBookMix($total > 0.0 ? $mortgage / $total : self::DEFAULT_MORTGAGE_BOOK_SHARE, 0.0, 0.0);
    }

    /** @return array{residential: float, consumer: float, commercial_real_estate: float, business: float} */
    protected function resolveDefaultLoanBookMix(): array
    {
        return self::completeLoanBookMix(self::DEFAULT_MORTGAGE_BOOK_SHARE, 0.0, 0.0);
    }

    /** A shadow bank's revenue target is struck on its operating margin (getTargetMetrics), so its cost base is that margin's complement. */
    public function getOperatingCostToEarningAssets(Stock $stock): ?float
    {
        return null;
    }

    public function getCreditLossHorizonYears(): float
    {
        return self::CECL_LIFETIME_HORIZON_YEARS;
    }

    public function calculateInterestIncome(Stock $stock, MacroStateDTO $macroState, MathUtility $mathUtility, ?float $realizedWholesaleRate = null): float
    {
        // The portfolio is struck on the funded book, not the term notes alone: interest expense runs on
        // getTotalDebt(), so a leg priced off getWholesaleDebt() left drawn revolver paying a coupon against
        // no asset. A shadow bank deploys its funding, so this reads the live earning-asset ledger.
        $fundedBook = $this->resolveEarningAssets($stock);
        $treasury = (float) $stock->getCorporateTreasury();

        $params = $this->resolveModelParameters($stock, [
            ModelParam::MortgageOriginationWeight->value => 0.60,
            ModelParam::DirectLendingWeight->value       => 0.40,
        ]);

        $mortgageWeight = $params[ModelParam::MortgageOriginationWeight];
        $lendingWeight  = $params[ModelParam::DirectLendingWeight];
        $totalWeight = $mortgageWeight + $lendingWeight;
        if ($totalWeight > 0.0) {
            $mortgageWeight /= $totalWeight;
            $lendingWeight  /= $totalWeight;
        }

        // 1. Mortgage Portfolio Interest Income (Agency / Non-Agency MBS and residential whole loans):
        // Backed by long-term mortgage yields benchmarked to 30Y Treasury yield + portfolio mortgage spread.
        $mortgageYield = max(0.01, $macroState->yield30yEma + self::MORTGAGE_PORTFOLIO_SPREAD);
        $mortgageInterest = ($fundedBook * $mortgageWeight) * $mortgageYield;

        // 2. Direct Lending / Private Credit Floating-Rate Loan Portfolio:
        // Senior secured middle-market loans float over overnight policy rate (SOFR) + illiquidity spread.
        $policyRate = $macroState->policyRateEma;
        $directLendingYield = max(0.01, $policyRate + self::DIRECT_LENDING_PORTFOLIO_SPREAD);
        $directLendingInterest = ($fundedBook * $lendingWeight) * $directLendingYield;

        // 3. Excess Treasury Liquidity Yield:
        $operatingBase = $this->getOperatingBase($stock);
        $excessCash = max(0.0, $treasury - ($operatingBase * self::TARGET_OPERATING_BUFFER));
        $cashInterest = $excessCash * $this->calculateCashYield($macroState);

        return $mortgageInterest + $directLendingInterest + $cashInterest;
    }

    public function getTargetMetrics(Stock $stock, MacroStateDTO $macroState, MathUtility $mathUtility): array
    {
        // Capital is tangible: goodwill absorbs no loss, so it neither sizes the book nor earns the return target.
        $equity = $stock->getTangibleEquity();
        $wholesaleDebt = (float) $stock->getWholesaleDebt();
        $treasury = (float) $stock->getCorporateTreasury();

        $effectiveEquity = max(1.0, $equity);
        $earningAssets = max($effectiveEquity, $effectiveEquity + $wholesaleDebt - $treasury);
        $baselineRoe = $this->resolveStructuralTargetRoe($stock, $macroState);
        $stableMargin = max(0.01, (float) $stock->getOperatingMargin());

        $policyRate = $macroState->policyRateEma;
        $yield5y = $macroState->yield5yEma;
        $structuralSpread = (float) $stock->getCreditSpread();
        $floatingRatio = (float) $stock->getFloatingDebtRatio();

        $taxRate = $macroState->corporateTaxRate;

        // Reverse-engineer the optimal EBIT needed to cover massive wholesale debt
        $optimalNetIncome = $equity * $baselineRoe;
        $optimalEbt = $optimalNetIncome / max(0.01, 1.0 - $taxRate);

        $floatingInterestRate = $policyRate + $structuralSpread;
        $optimalInterestExpense = ($wholesaleDebt * (1.0 - $floatingRatio) * (float) $stock->getHistoricalFixedRate())
            + ($wholesaleDebt * $floatingRatio * $floatingInterestRate);

        $operatingBase = $this->getOperatingBase($stock);
        $excessCash = max(0.0, $treasury - ($operatingBase * self::TARGET_OPERATING_BUFFER));
        $expectedTreasuryIncome = $excessCash * $this->calculateCashYield($macroState);

        $params = $this->resolveModelParameters($stock, [
            ModelParam::MortgageOriginationWeight->value => 0.60,
            ModelParam::DirectLendingWeight->value       => 0.40,
        ]);

        $mortgageWeight = $params[ModelParam::MortgageOriginationWeight];
        $lendingWeight  = $params[ModelParam::DirectLendingWeight];
        $totalWeight = $mortgageWeight + $lendingWeight;
        if ($totalWeight > 0.0) {
            $mortgageWeight /= $totalWeight;
            $lendingWeight  /= $totalWeight;
        }

        $mortgageYield = max(0.01, $macroState->yield30yEma + self::MORTGAGE_PORTFOLIO_SPREAD);
        $directLendingYield = max(0.01, $policyRate + self::DIRECT_LENDING_PORTFOLIO_SPREAD);
        $optimalInterestIncome = ($wholesaleDebt * $mortgageWeight * $mortgageYield)
            + ($wholesaleDebt * $lendingWeight * $directLendingYield)
            + $expectedTreasuryIncome;

        // Pre-provision: the portfolio charge-off rate is booked against EBIT by the allowance roll-forward,
        // so the ROE target is earned after it and the operating target has to fund it.
        $optimalCreditProvision = $this->resolveThroughTheCycleCreditProvision($stock, $earningAssets);
        $optimalEbit = $optimalEbt + $optimalInterestExpense - $optimalInterestIncome + $optimalCreditProvision;
        $minOperatingEbit = $earningAssets * self::MIN_OPERATING_EBIT_YIELD;
        $targetEbit = max($minOperatingEbit, $optimalEbit);

        $unboundedRevenue = max(0.0, $targetEbit) / $stableMargin;
        $targetRevenue = min($unboundedRevenue, $earningAssets * self::MAX_GROSS_ASSET_YIELD); // Hard cap gross yield at 50%

        $grossYield = $targetRevenue / max(1.0, abs($earningAssets));

        return [
            'invested_capital' => $earningAssets,
            'baseline_roic' => ($grossYield * $stableMargin) * (1.0 - $taxRate)
        ];
    }

    protected function calculateSectorPhysics(Stock $stock, float $expectedRevenue, float $realizedVariableMargin, float $fixedCosts, float $baselineVol, MacroStateDTO $macroState, MathUtility $mathUtility): SectorPhysicsResult
    {
        $momentum = $stock->getEarningsMomentumZ() ?? [];
        $streams  = $this->createStreamContext($momentum, $mathUtility, $macroState, $stock);

        $params = $this->resolveModelParameters($stock, [
            ModelParam::MortgageOriginationWeight->value => 0.60,
            ModelParam::DirectLendingWeight->value       => 0.40,
        ]);

        // --- Dynamic Revenue Mix Drift with Strategic Mean Reversion ---
        $activeWeights = $streams->resolveActiveStreamWeights([
            'origination_fees' => $params[ModelParam::MortgageOriginationWeight],
            'direct_lending'   => $params[ModelParam::DirectLendingWeight],
        ]);

        $mortgageWeight = $activeWeights['origination_fees'];
        $lendingWeight  = $activeWeights['direct_lending'];

        // Independent stream Z-scores
        $originationZ = $streams->generateZ('origination_fees', 0.20);
        $lendingZ     = $streams->generateZ('direct_lending', 0.45);

        // 1. Mortgage Origination Volume Channel:
        // Spiking 30Y mortgage rates destroy refinancing demand and freeze home purchases.
        // Strong residential property values and housing starts stimulate new mortgage purchase originations.
        $yield30y = $macroState->yield30yEma;
        $mortgageRateDrag = max(0.0, ($yield30y - self::DEFAULT_30Y_YIELD_FALLBACK) * 4.0);
        $residentialShift = ($macroState->residentialPropertyIndexEma - 100.0) / 100.0;
        $propertyOriginationBoost = $residentialShift * 0.20;
        $housingStartsShift = MathUtility::calculateHousingStartsShift($macroState->housingStartsIndexEma, sensitivity: self::HOUSING_STARTS_ORIGINATION_SENSITIVITY);

        // 2. Direct Lending Floating-Rate Channel:
        // Private debt / direct lending loans float on base policy rates (SOFR + spread), expanding yield during high-rate regimes.
        // Bank credit retreat (SLOOS tightening) and M2 systemic liquidity stimulate private credit borrower migration.
        $policyRate = $macroState->policyRateEma;
        $directLendingRateBonus = max(0.0, ($policyRate - 0.03) * 1.5);
        $sloosDirectLendingBoost = max(0.0, $macroState->sloosTighteningIndexEma) * self::SLOOS_PRIVATE_CREDIT_EXPANSION;
        $m2Shift = MathUtility::calculateBroadMoneyLiquidityShift($macroState->moneySupplyGrowthEma, sensitivity: self::M2_SHADOW_LIQUIDITY_SENSITIVITY);
        $capitalTightness = max(0.0, $macroState->countercyclicalBufferRateEma) + ($macroState->bankCapitalRequirement - FinancialConstants::OPENING_BANK_CAPITAL_REQUIREMENT);
        $ccybArbitrageBoost = $capitalTightness * self::CAPITAL_ARBITRAGE_SENSITIVITY;

        $mortgageRevenue = max(0.0, $expectedRevenue * $mortgageWeight * (1.0 + ($originationZ * ($baselineVol * self::REVENUE_VARIANCE_SCALAR * 1.5)) - $mortgageRateDrag + $propertyOriginationBoost + $housingStartsShift));
        $lendingRevenue  = max(0.0, $expectedRevenue * $lendingWeight * (1.0 + ($lendingZ * ($baselineVol * self::REVENUE_VARIANCE_SCALAR * 0.8)) + $directLendingRateBonus + $sloosDirectLendingBoost + $m2Shift + $ccybArbitrageBoost));
        
        $streamRevenues = [
            'origination_fees' => $mortgageRevenue,
            'direct_lending'   => $lendingRevenue,
        ];

        $actualRevenue = max(0.0, array_sum($streamRevenues));
        $streams->recordStreamShares($streamRevenues);

        // Charge-offs are the book's conditional loss at the household and corporate default cycles, mortgages losing
        // more as homes fall below the price they were lent against (the bank segment model). They reach EBIT once,
        // through the allowance roll-forward; the forward-looking CECL reserve moves the allowance TARGET through
        // getForwardCreditLossMultiplier(). Neither is a margin term.
        $credit = $this->resolveConditionalCreditLossRate($stock, $macroState, $streams, $mathUtility);
        $netChargeOffs = ($credit['loss_rate'] / FinancialConstants::QUARTERS_PER_YEAR) * $this->resolveEarningAssets($stock);
        $lossMultiple = $credit['loss_rate'] / max(1e-9, $this->getThroughTheCycleCreditLossRate($stock));

        // Shadow Bank NIM Squeeze (high VULNERABILITY):
        $mortgageSpread = $yield30y - ($policyRate + $macroState->interbankLiquiditySpreadEma);

        if ($mortgageSpread < 0) {
            $nimSqueeze = (self::TARGET_MORTGAGE_SPREAD - $mortgageSpread) * self::NIM_LINEAR_SENSITIVITY + pow(abs($mortgageSpread) * (FinancialConstants::YIELD_CURVE_INVERSION_SENSITIVITY * self::NIM_INVERSION_SCALAR), 2) * self::NIM_QUADRATIC_COEFF;
        } else {
            $nimSqueeze = (self::TARGET_MORTGAGE_SPREAD - $mortgageSpread) * self::NIM_LINEAR_SENSITIVITY;
        }

        $minVariableMargin = max(0.01, self::MIN_EFFICIENCY_RATIO - ($fixedCosts / max(1.0, $actualRevenue)));
        $clampedMargin = $this->clampMargin($realizedVariableMargin + $nimSqueeze, $minVariableMargin);

        $eventType = null;
        if ($lossMultiple > static::SECTOR_SHOCK_MASSIVE_LOSS_MULTIPLE) {
            $eventType = ShockEvent::MASSIVE_CREDIT_PROVISION;
        } elseif ($lossMultiple > static::SECTOR_SHOCK_ELEVATED_LOSS_MULTIPLE) {
            $eventType = ShockEvent::ELEVATED_LOAN_DEFAULTS;
        } elseif ($lossMultiple < static::SECTOR_SHOCK_RESERVE_RELEASE_LOSS_MULTIPLE) {
            $eventType = ShockEvent::RESERVE_RELEASE;
        }

        $primaryShockZ = $streams->resolveDominantShockZ([$credit['systematic_z'], $originationZ, $lendingZ]);

        $mortgageBase = max(1.0, $expectedRevenue * $mortgageWeight);
        $mortgageShock = ($mortgageRevenue - $mortgageBase) / $mortgageBase;
        $lendingBase = max(1.0, $expectedRevenue * $lendingWeight);
        $lendingShock = ($lendingRevenue - $lendingBase) / $lendingBase;
        $observableShockZ = ($mortgageShock * $mortgageWeight) + ($lendingShock * $lendingWeight);

        return new SectorPhysicsResult(
            actualRevenue: $actualRevenue,
            rawVariableMargin: $clampedMargin,
            primaryShockZ: $primaryShockZ,
            observableShockZ: $observableShockZ,
            eventType: $eventType,
            streamZ: $streams->getStreamZ(),
            streamRevenue: $streamRevenues,
            netChargeOffs: $netChargeOffs,
        );
    }

    /**
     * Shadow banks lack customer deposits and fund their entire loan portfolio via wholesale debt and repo facilities.
     */
    public function supportsUnderleveragedDebtExpansion(): bool
    {
        return true;
    }

    /**
     * MacroStateDTO fields (snake_case) this model's operating physics genuinely reads in
     * calculateSectorPhysics()/getMacroPhysics() — see OperatingStrategyInterface for the full rule.
     *
     * @return list<string>
     */
    public function getOperatingMacroFields(): array
    {
        return [
            'bank_capital_requirement',
            'commercial_property_index_ema',
            'corporate_default_rate_ema',
            'countercyclical_buffer_rate_ema',
            'housing_starts_index_ema',
            'inflation_ema',
            'interbank_liquidity_spread_ema',
            'macro_credit_spread_ema',
            'money_market_fund_share',
            'money_market_fund_share_ema',
            'money_supply_growth_ema',
            'output_gap_lag_9m',
            'policy_rate_ema',
            'recession_probability_ema',
            'residential_property_index_ema',
            'retail_default_rate_ema',
            'sloos_tightening_index_ema',
            'yield_30y_ema',
        ];
    }
}
