<?php

declare(strict_types=1);

namespace App\Service\Model\Sector;

use App\Service\Model\BusinessModelInterface;

use App\Data\ModelParam;
use App\DTO\MacroStateDTO;
use App\DTO\SectorPhysicsResult;
use App\Entity\Stock;
use App\Service\Math\MathUtility;
use App\Service\Macro\MacroEngine;
use App\Service\Event\ShockEvent;
use App\Service\Math\FinancialConstants;

/**
 * Earnings strategy for Shadow Banks (Mortgage Finance, Non-bank lenders).
 * 
 * Financial Physics:
 * - Operates like a bank but without customer deposits.
 * - Funds its entire loan book via Wholesale Debt (Repo Markets, Commercial Paper).
 * - Highly vulnerable to credit market freezes and yield curve inversions.
 * - Evaluated on Return on Equity (ROE).
 */
class ShadowBankBusinessModel extends CommercialBankBusinessModel
{
    // --- Bank Levy ---
    /** A non-bank lender funded in the markets is outside the bank levy. */
    public const PAYS_BANK_LEVY = false;

    // --- Prudential Regulation ---
    /** A shadow bank takes no deposits and sits outside the District's bank capital requirement. */
    public const PRUDENTIALLY_REGULATED = false;

    // --- Operating Cyclicality & Demand Structure ---
    /** Elasticity of volumes and costs to the macro cycle (1.0 = one for one with the output gap). Wholesale-funded lending expands and contracts with credit conditions. */
    public const OPERATING_CYCLICALITY = 1.30;

    // --- Analyst Visibility & Error ---
    public const BASE_COVERAGE_VISIBILITY = 0.50;
    public const BASE_COVERAGE_ERROR = 0.10;
    public function getWholesaleLeverageLimit(): float { return 8.0; }
    public function getMoatSpread(): float { return 0.005; }

    // --- Portfolio & Asset Yield Architecture ---
    /**
     * A thirty-year mortgage book, priced off the long end and funded overnight. Longer than a deposit
     * bank's loan book by the whole of the difference between the two businesses, which is why a shadow
     * bank is the first thing a hiking cycle breaks.
     */
    public const ASSET_DURATION_YEARS = 8.0;

    /** Yield spread over the 30Y benchmark the mortgage portfolio is priced at when the franchise is struck. */
    public const MORTGAGE_PORTFOLIO_SPREAD = 0.0225;
    /** Spread over SOFR on direct loans: 500-700bp on the Cliffwater Direct Lending Index in 2023 (as reported by Swedroe 2023); the midpoint. */
    public const DIRECT_LENDING_PORTFOLIO_SPREAD = 0.060;
    /** Share of the direct loans at floating rates: almost all private credit loans float (Federal Reserve FEDS Note, "Private Credit: Characteristics and Risks", 2024). */
    public const DIRECT_LENDING_FLOATING_SHARE = 1.0;
    /** Minimum baseline operating EBIT yield generated by origination and servicing operations. */
    public const MIN_OPERATING_EBIT_YIELD = 0.015;

    // --- ROE & Target Architecture ---
    /** Target operating cash reserve ratio applied to corporate operating base. */
    public const TARGET_OPERATING_BUFFER  = 0.05;
    /** Hard ceiling on gross asset yield to prevent reverse-engineered revenue hyperinflation. */
    public const MAX_GROSS_ASSET_YIELD    = 0.50;

    // --- Credit Losses (ASC 326) ---
    /** Default mortgage share of the book (MortgageOriginationWeight), lent against homes; direct lending takes the rest as business credit. Through the cycle the blend loses ~0.55% a year at the bank segment rates. */
    public const DEFAULT_MORTGAGE_BOOK_SHARE = 0.60;
    /** Years of expected loss the allowance covers: mortgages prepay and middle-market loans mature well inside their contractual terms. */
    public const CECL_LIFETIME_HORIZON_YEARS = 3.0;

    // --- Revenue Shock Physics ---
    /** Volatility multiplier for top-line revenue shocks in non-bank lending markets. */
    public const REVENUE_VARIANCE_SCALAR = 0.20;
    /** Lifetime-loss multiplier per unit of IG spread widening on a leveraged private-credit book: +300bps lifts the reserve target ~0.30x. */
    public const CECL_RESERVE_SPREAD_SENSITIVITY = 10.0;
    /** Direct lending volume per unit of capital the regulated banks must hold beyond the District's opening requirement, the countercyclical buffer included: a bank syndicate with 1pp less Tier 1 headroom leaves 1.547pp more of a loan to nonbanks, on a 23.1% mean nonbank share (Irani, Iyer, Meisenzahl & Peydro 2021, RFS, Table 5 col. 1); the Basel III shock in their fn. 33 is six times larger. */
    public const CAPITAL_ARBITRAGE_SENSITIVITY = 6.70;
    /** Structural minimum operating cost-to-revenue ratio for non-bank lending operations. */
    public const MIN_EFFICIENCY_RATIO      = 0.45;

    // --- Private Credit & Corporate Default Physics ---
    /** Baseline investment-grade credit spread for normal shadow bank portfolio lending, the macro through-the-cycle IG spread. */
    public const CECL_BASELINE_CREDIT_SPREAD    = MacroEngine::BASE_CREDIT_SPREAD;
    /** Expansion sensitivity of direct lending origination when commercial banks tighten credit standards (SLOOS). */
    public const SLOOS_PRIVATE_CREDIT_EXPANSION = 0.30;
    /** Baseline 12-month forward recession probability; the lifetime loss estimate is struck at 1.0x here. */
    public const CECL_BASELINE_RECESSION_PROB   = 0.15;
    /** Lifetime-loss multiplier per unit of recession probability above baseline: a near-certain recession lifts the reserve target ~0.85x. */
    public const CECL_RESERVE_RECESSION_SENSITIVITY = 1.00;

    // --- Housing Starts & M2 Liquidity Transmission ---
    /** Sensitivity of non-bank purchase mortgage originations to residential housing starts. */
    public const HOUSING_STARTS_ORIGINATION_SENSITIVITY = 0.35;
    /** Sensitivity of private credit deployment and wholesale repo funding to M2 money supply growth. */
    public const M2_SHADOW_LIQUIDITY_SENSITIVITY = 0.30;

    // --- Mortgage Origination ---
    /** 30Y Treasury yield above which refinancing and purchase origination volume falls. */
    public const DEFAULT_30Y_YIELD_FALLBACK = 0.045;

    // --- Analyst Visibility & Error ---
    // Moved to getCoverageProfile() — see MarketConsensusEngine.

    /**
     * The book is the two portfolios the revenue streams earn on: mortgages, secured on homes, and direct loans to
     * middle-market firms, charged off at the bank segment rates.
     *
     * @return array{residential: float, consumer: float, commercial_real_estate: float, business: float}
     */
    protected function resolveLoanBookMix(Stock $stock): array
    {
        $params = $this->resolveModelParameters($stock, [
            ModelParam::MortgageOriginationWeight->value => self::DEFAULT_MORTGAGE_BOOK_SHARE,
            ModelParam::DirectLendingWeight->value       => 1.0 - self::DEFAULT_MORTGAGE_BOOK_SHARE,
        ]);
        $mortgage = max(0.0, (float) $params[ModelParam::MortgageOriginationWeight]);
        $total = $mortgage + max(0.0, (float) $params[ModelParam::DirectLendingWeight]);

        return self::completeLoanBookMix($total > 0.0 ? $mortgage / $total : self::DEFAULT_MORTGAGE_BOOK_SHARE, 0.0, 0.0);
    }

    /** @return array{residential: float, consumer: float, commercial_real_estate: float, business: float} */
    protected function resolveDefaultLoanBookMix(): array
    {
        return self::completeLoanBookMix(self::DEFAULT_MORTGAGE_BOOK_SHARE, 0.0, 0.0);
    }

    /** A shadow bank's revenue target is struck on its operating margin (getTargetMetrics), so its cost base is that margin's complement. */
    public function getOperatingCostToEarningAssets(Stock $stock): ?float
    {
        return null;
    }

    public function getCreditLossHorizonYears(): float
    {
        return self::CECL_LIFETIME_HORIZON_YEARS;
    }

    /**
     * Interest earned on the funded book as it has repriced (resolveInterestYield()), plus treasury income on the
     * excess cash. The book is struck on the live earning-asset ledger, not the term notes alone, so drawn revolver
     * funds assets that earn.
     */
    public function calculateInterestIncome(Stock $stock, MacroStateDTO $macroState, MathUtility $mathUtility, ?float $realizedWholesaleRate = null): float
    {
        $bookInterest = $this->resolveEarningAssets($stock) * $this->resolveInterestYield($stock, $macroState);
        $excessCash = max(0.0, (float) $stock->getCorporateTreasury() - ($this->getOperatingBase($stock) * self::TARGET_OPERATING_BUFFER));

        return $bookInterest + ($excessCash * $this->calculateCashYield($macroState));
    }

    /**
     * Operating revenue is origination and servicing fees, a fee yield on the book struck once at the opening macro
     * (resolveFranchisePricing()). The rate cycle reaches profit through the book's interest income and the wholesale
     * funding cost, not through a revenue target re-solved every quarter to hold the return.
     *
     * @return array{invested_capital: float, baseline_roic: float}
     */
    public function getTargetMetrics(Stock $stock, MacroStateDTO $macroState, MathUtility $mathUtility): array
    {
        $stableMargin = max(0.01, (float) $stock->getOperatingMargin());

        return [
            'invested_capital' => $this->resolveEarningAssets($stock),
            'baseline_roic' => $this->resolveFranchisePricing($stock)['fee_yield'] * $stableMargin * (1.0 - $macroState->corporateTaxRate),
        ];
    }

    /**
     * The franchise's pricing, struck once at the opening macro: the direct loans float (a bank's deposit-matching
     * line has no deposits here to match); the loan spread puts the
     * book's yield where its two portfolios are priced (mortgages over the 30-year, direct loans over SOFR); the fee
     * yield is the operating revenue the lender's structural return requires on top of that book at the opening
     * funding cost and the through-the-cycle credit charge.
     *
     * @return array{floating_share: float, loan_spread: float, fee_yield: float}
     */
    protected function resolveFranchisePricing(Stock $stock): array
    {
        $momentum = $stock->getEarningsMomentumZ() ?? [];
        if (isset($momentum[self::STATE_FLOATING_LOAN_SHARE], $momentum[self::STATE_LOAN_SPREAD], $momentum[self::STATE_FEE_YIELD])) {
            return [
                'floating_share' => (float) $momentum[self::STATE_FLOATING_LOAN_SHARE],
                'loan_spread' => (float) $momentum[self::STATE_LOAN_SPREAD],
                'fee_yield' => (float) $momentum[self::STATE_FEE_YIELD],
            ];
        }

        $opening = new MacroStateDTO();
        $mortgageShare = $this->resolveLoanBookMix($stock)['residential'];
        $bookYield = ($mortgageShare * ($opening->yield30yEma + self::MORTGAGE_PORTFOLIO_SPREAD))
            + ((1.0 - $mortgageShare) * ($opening->policyRateEma + self::DIRECT_LENDING_PORTFOLIO_SPREAD));
        $loanSpread = ($bookYield - $this->resolveMarketInterestYield($stock, $opening, self::DIRECT_LENDING_FLOATING_SHARE))
            / max(1e-9, $this->getLoanShareOfEarningAssets());

        return [
            'floating_share' => self::DIRECT_LENDING_FLOATING_SHARE,
            'loan_spread' => $loanSpread,
            'fee_yield' => $this->resolveCalibrationFeeYield($stock, $opening, $bookYield),
        ];
    }

    /**
     * The operating revenue per unit of book that earns the structural return at a macro state, given the book's
     * interest yield: target pre-tax profit plus wholesale funding cost and the through-the-cycle credit charge, less
     * the book's and the cash's interest, grossed up by the operating margin.
     */
    private function resolveCalibrationFeeYield(Stock $stock, MacroStateDTO $macroState, float $bookYield): float
    {
        $earningAssets = $this->resolveEarningAssets($stock);
        $wholesaleDebt = (float) $stock->getWholesaleDebt();
        $floatingRatio = (float) $stock->getFloatingDebtRatio();
        $stableMargin = max(0.01, (float) $stock->getOperatingMargin());

        $targetEbt = max(1.0, $stock->getTangibleEquity()) * $this->resolveCalibrationRoe($stock, $macroState) / max(0.01, 1.0 - $macroState->corporateTaxRate);
        $interestExpense = ($wholesaleDebt * (1.0 - $floatingRatio) * (float) $stock->getHistoricalFixedRate())
            + ($wholesaleDebt * $floatingRatio * ($macroState->policyRateEma + (float) $stock->getCreditSpread()));
        $excessCash = max(0.0, (float) $stock->getCorporateTreasury() - ($this->getOperatingBase($stock) * self::TARGET_OPERATING_BUFFER));
        $interestIncome = ($earningAssets * $bookYield) + ($excessCash * $this->calculateCashYield($macroState));

        $targetEbit = max(
            $earningAssets * self::MIN_OPERATING_EBIT_YIELD,
            $targetEbt + $interestExpense - $interestIncome + $this->resolveThroughTheCycleCreditProvision($stock, $earningAssets)
        );

        return min($targetEbit / $stableMargin, $earningAssets * self::MAX_GROSS_ASSET_YIELD) / max(1.0, $earningAssets);
    }

    /**
     * A direct loan resets over SOFR, a secured overnight rate that follows the policy rate and not the unsecured
     * interbank market: an interbank freeze raises the lender's wholesale funding cost without lifting what it earns.
     *
     * @return array{floating: float, fixed: float, residential: float, securities: float}
     */
    protected function resolveRepricingRates(Stock $stock, MacroStateDTO $macroState): array
    {
        return ['floating' => $macroState->policyRateEma] + parent::resolveRepricingRates($stock, $macroState);
    }

    protected function calculateSectorPhysics(Stock $stock, float $expectedRevenue, float $realizedVariableMargin, float $fixedCosts, float $baselineVol, MacroStateDTO $macroState, MathUtility $mathUtility): SectorPhysicsResult
    {
        $momentum = $stock->getEarningsMomentumZ() ?? [];
        $streams  = $this->createStreamContext($momentum, $mathUtility, $macroState, $stock);

        $params = $this->resolveModelParameters($stock, [
            ModelParam::MortgageOriginationWeight->value => 0.60,
            ModelParam::DirectLendingWeight->value       => 0.40,
        ]);

        // --- Dynamic Revenue Mix Drift with Strategic Mean Reversion ---
        $activeWeights = $streams->resolveActiveStreamWeights([
            'origination_fees' => $params[ModelParam::MortgageOriginationWeight],
            'direct_lending'   => $params[ModelParam::DirectLendingWeight],
        ]);

        $mortgageWeight = $activeWeights['origination_fees'];
        $lendingWeight  = $activeWeights['direct_lending'];

        // Independent stream Z-scores
        $originationZ = $streams->generateZ('origination_fees', 0.20);
        $lendingZ     = $streams->generateZ('direct_lending', 0.45);

        // 1. Mortgage Origination Volume Channel:
        // Spiking 30Y mortgage rates destroy refinancing demand and freeze home purchases.
        // Strong residential property values and housing starts stimulate new mortgage purchase originations.
        $yield30y = $macroState->yield30yEma;
        $mortgageRateDrag = max(0.0, ($yield30y - self::DEFAULT_30Y_YIELD_FALLBACK) * 4.0);
        $residentialShift = ($macroState->residentialPropertyIndexEma - 100.0) / 100.0;
        $propertyOriginationBoost = $residentialShift * 0.20;
        $housingStartsShift = MathUtility::calculateHousingStartsShift($macroState->housingStartsIndexEma, sensitivity: self::HOUSING_STARTS_ORIGINATION_SENSITIVITY);

        // 2. Direct Lending Origination Channel:
        // The loans' floating coupon is interest income on the book (calculateInterestIncome()); this stream is the
        // fees on new deals, which bank credit retreat (SLOOS tightening) and M2 liquidity send to private credit.
        $sloosDirectLendingBoost = max(0.0, $macroState->sloosTighteningIndexEma) * self::SLOOS_PRIVATE_CREDIT_EXPANSION;
        $m2Shift = MathUtility::calculateBroadMoneyLiquidityShift($macroState->moneySupplyGrowthEma, $macroState->moneySupplyGrowthTrend, sensitivity: self::M2_SHADOW_LIQUIDITY_SENSITIVITY);
        $capitalTightness = max(0.0, $macroState->countercyclicalBufferRateEma) + ($macroState->bankCapitalRequirement - FinancialConstants::OPENING_BANK_CAPITAL_REQUIREMENT);
        $ccybArbitrageBoost = $capitalTightness * self::CAPITAL_ARBITRAGE_SENSITIVITY;

        $mortgageRevenue = max(0.0, $expectedRevenue * $mortgageWeight * (1.0 + ($originationZ * ($baselineVol * self::REVENUE_VARIANCE_SCALAR * 1.5)) - $mortgageRateDrag + $propertyOriginationBoost + $housingStartsShift));
        $lendingRevenue  = max(0.0, $expectedRevenue * $lendingWeight * (1.0 + ($lendingZ * ($baselineVol * self::REVENUE_VARIANCE_SCALAR * 0.8)) + $sloosDirectLendingBoost + $m2Shift + $ccybArbitrageBoost));
        
        $streamRevenues = [
            'origination_fees' => $mortgageRevenue,
            'direct_lending'   => $lendingRevenue,
        ];

        $actualRevenue = max(0.0, array_sum($streamRevenues));
        $streams->recordStreamShares($streamRevenues);

        // Charge-offs are the book's conditional loss at the household and corporate default cycles, mortgages losing
        // more as homes fall below the price they were lent against (the bank segment model). They reach EBIT once,
        // through the allowance roll-forward; the forward-looking CECL reserve moves the allowance TARGET through
        // getForwardCreditLossMultiplier(). Neither is a margin term.
        $credit = $this->resolveConditionalCreditLossRate($stock, $macroState, $streams, $mathUtility);
        $netChargeOffs = ($credit['loss_rate'] / FinancialConstants::QUARTERS_PER_YEAR) * $this->resolveEarningAssets($stock);
        $lossMultiple = $credit['loss_rate'] / max(1e-9, $this->getThroughTheCycleCreditLossRate($stock));

        // Rate risk is the repricing gap itself: the mortgage book reprices over years while the repo funding resets
        // at once, so a flat or inverted curve reaches profit through interest income and expense, not the cost ratio.
        $this->advanceBookYields($stock, $macroState, $streams, $mathUtility);
        $minVariableMargin = max(0.01, self::MIN_EFFICIENCY_RATIO - ($fixedCosts / max(1.0, $actualRevenue)));
        $clampedMargin = $this->clampMargin($realizedVariableMargin, $minVariableMargin);

        $eventType = null;
        if ($lossMultiple > static::SECTOR_SHOCK_MASSIVE_LOSS_MULTIPLE) {
            $eventType = ShockEvent::MASSIVE_CREDIT_PROVISION;
        } elseif ($lossMultiple > static::SECTOR_SHOCK_ELEVATED_LOSS_MULTIPLE) {
            $eventType = ShockEvent::ELEVATED_LOAN_DEFAULTS;
        } elseif ($lossMultiple < static::SECTOR_SHOCK_RESERVE_RELEASE_LOSS_MULTIPLE) {
            $eventType = ShockEvent::RESERVE_RELEASE;
        }

        $primaryShockZ = $streams->resolveDominantShockZ([$credit['systematic_z'], $originationZ, $lendingZ]);

        $mortgageBase = max(1.0, $expectedRevenue * $mortgageWeight);
        $mortgageShock = ($mortgageRevenue - $mortgageBase) / $mortgageBase;
        $lendingBase = max(1.0, $expectedRevenue * $lendingWeight);
        $lendingShock = ($lendingRevenue - $lendingBase) / $lendingBase;
        $observableShockZ = ($mortgageShock * $mortgageWeight) + ($lendingShock * $lendingWeight);

        return new SectorPhysicsResult(
            actualRevenue: $actualRevenue,
            rawVariableMargin: $clampedMargin,
            primaryShockZ: $primaryShockZ,
            observableShockZ: $observableShockZ,
            eventType: $eventType,
            streamZ: $streams->getStreamZ(),
            streamRevenue: $streamRevenues,
            netChargeOffs: $netChargeOffs,
        );
    }

    /**
     * Shadow banks lack customer deposits and fund their entire loan portfolio via wholesale debt and repo facilities.
     */
    public function supportsUnderleveragedDebtExpansion(): bool
    {
        return true;
    }

    /**
     * MacroStateDTO fields (snake_case) this model's operating physics genuinely reads in
     * calculateSectorPhysics()/getMacroPhysics() — see OperatingStrategyInterface for the full rule.
     *
     * @return list<string>
     */
    public function getOperatingMacroFields(): array
    {
        return [
            'bank_capital_requirement',
            'commercial_property_index_ema',
            'corporate_default_rate_ema',
            'countercyclical_buffer_rate_ema',
            'housing_starts_index_ema',
            'inflation_ema',
            'interbank_liquidity_spread_ema',
            'macro_credit_spread_ema',
            'money_market_fund_share',
            'money_market_fund_share_ema',
            'money_supply_growth_ema',
            'money_supply_growth_trend',
            'output_gap_lag_9m',
            'policy_rate_ema',
            'recession_probability_ema',
            'residential_property_index_ema',
            'retail_default_rate_ema',
            'sloos_tightening_index_ema',
            'system_deposit_beta_ema',
            'yield_10y_ema',
            'yield_2y_ema',
            'yield_30y_ema',
            'yield_5y_ema',
        ];
    }
}
