<?php

declare(strict_types=1);

namespace App\DTO;

/**
 * Immutable Data Transfer Object representing the actual financial outcomes generated by a Business Model.
 * Replaces the former ShockResult DTO. Contains no analyst or consensus data.
 */
readonly class ActualFinancialsDTO
{
    /**
     * @param float                $actualRevenue         Realized revenue after sector physics and shocks.
     * @param float                $actualVariableCosts   Realized variable costs after margin clamping.
     * @param float                $clampedMargin         The margin ratio used (needed by MarketConsensusEngine).
     * @param float                $ebit                  Earnings Before Interest & Tax.
     * @param float                $primaryShockZ         The dominant idiosyncratic Z-score driving this quarter's shock.
     * @param float                $observableShockZ      The fraction of the shock exposed to public data (used by MarketConsensusEngine).
     * @param string|null          $eventType             Named event type if a tail-risk event fired, otherwise null.
     * @param array<string, mixed> $eventContext          Optional key-value lore context for the NarrativeEngine.
     * @param bool|null            $isPublicEvent         For event-conditional models: true when a binary public event occurred.
     * @param array<string, float> $streamZ               Dictionary of individual AR(1) stream Z-scores to persist.
     * @param array<string, float> $streamRevenue         Dictionary of absolute dollar revenue generated per stream.
     * @param float                $scheduledCapex        Mandatory quarterly CapEx committed by the sector physics.
     * @param array<string, float> $kpis                  Reported operating KPIs (book_to_bill, subscriber_index...).
     */
    public function __construct(
        public float $actualRevenue,
        public float $actualVariableCosts,
        public float $clampedMargin,
        public float $ebit,
        public float $primaryShockZ,
        public float $observableShockZ,
        public ?string $eventType = null,
        public array $eventContext = [],
        public ?bool $isPublicEvent = null,
        public array $streamZ = [],
        public array $streamRevenue = [],
        public float $scheduledCapex = 0.0,
        public array $kpis = [],
    ) {}
}
