<?php

namespace App\Service\Math;

use App\Service\Macro\MacroEngine;

/**
 * Utility service for advanced mathematical operations required by the simulation engine.
 */
class MathUtility
{
    private static ?self $instance = null;

    public static function getInstance(): self
    {
        return self::$instance ??= new self();
    }

    /**
     * @var float|null Stores the second random number generated by the Box-Muller transform.
     */
    private ?float $spareNormal = null;

    private float $randMaxInverse;
    private float $twoPi;

    /**
     * Constructor for MathUtility.
     * Pre-calculates constants for random number generation.
     */
    public function __construct()
    {
        $this->randMaxInverse = 1.0 / mt_getrandmax();
        $this->twoPi = 2.0 * M_PI;
    }

    /**
     * Formats a float into a non-scientific decimal string suitable for database storage.
     * Prevents exponential notation (e.g., 1.0E-5) and guards against NaN or infinite values.
     *
     * @param float $value The numeric value to format.
     * @param int   $scale The number of decimal places (default 4).
     * @return string Formatted decimal string.
     */
    public static function formatDecimal(float $value, int $scale = 4): string
    {
        if (is_nan($value) || is_infinite($value)) {
            return number_format(0.0, $scale, '.', '');
        }

        return number_format($value, $scale, '.', '');
    }

    /**
     * Generates a random float between 0 and 1 from a uniform distribution.
     *
     * @return float A random float in the interval [0, 1].
     */
    public function generateUniform(): float
    {
        return mt_rand() * $this->randMaxInverse;
    }

    /**
     * Generates a random float between $min and $max from a uniform distribution.
     */
    public function generateUniformBetween(float $min, float $max): float
    {
        return $min + $this->generateUniform() * ($max - $min);
    }

    /**
     * Checks if an event occurs given a specific probability [0, 1].
     *
     * @param float $probability The probability of the event occurring.
     * @return bool True if the event occurred, false otherwise.
     */
    public function checkProbability(float $probability): bool
    {
        return $this->generateUniform() < $probability;
    }

    /**
     * Generates a random number from a standard normal distribution (Gaussian).
     *
     * This method uses the Box-Muller transform to convert uniformly distributed
     * random numbers (from mt_rand) into normally distributed numbers with
     * a mean of 0 and a standard deviation of 1.
     *
     * Since Box-Muller generates two numbers at once, one is returned immediately
     * and the other is stored in $spareNormal for the next call.
     *
     * @return float A random number following a standard normal distribution.
     */
    public function generateStandardNormal(): float
    {
        if ($this->spareNormal !== null) {
            $result = $this->spareNormal;
            $this->spareNormal = null;
            return $result;
        }

        do {
            $x = $this->generateUniform();
            $y = $this->generateUniform();
        } while ($x <= 0);

        $radius = sqrt(-2 * log($x));
        $angle = $this->twoPi * $y;

        $this->spareNormal = $radius * sin($angle);
        return $radius * cos($angle);
    }

    /**
     * Generates an AR(1) persistent Z-score for autoregressive dynamics.
     * Preserves unit variance (σ = 1.0) of the underlying stationary distribution.
     *
     * @param float $previousZ The previous quarter's realized Z-score (z_{t-1}).
     * @param float $phi       The autoregressive persistence coefficient (0 = i.i.d., 1 = random walk).
     * @return float The new Z-score z_t.
     */
    public function generatePersistentZ(float $previousZ, float $phi): float
    {
        $innovation = $this->generateStandardNormal();
        $innovationScale = sqrt(max(0.0, 1.0 - ($phi * $phi)));

        return ($phi * $previousZ) + ($innovationScale * $innovation);
    }

    /**
     * Converts a per-step persistence coefficient into the scale factor that preserves integrated variance.
     *
     * A sequence of N i.i.d. unit-variance shocks sums to variance N. Making those shocks autocorrelated with
     * coefficient phi inflates the sum's variance to approximately N * (1 + phi) / (1 - phi), so simply
     * swapping an i.i.d. driver for a persistent one silently multiplies realized volatility -- by more than
     * twenty times at the persistence levels used for a market factor on a fine time step. Scaling each shock
     * by this factor restores the original integrated variance while keeping the autocorrelation structure,
     * so persistence changes the SHAPE of the path (trends and regimes) without changing its magnitude.
     *
     * @param float $phi The autoregressive persistence coefficient in [0, 1).
     * @return float The multiplicative scale preserving the integrated variance of the shock sequence.
     */
    public function calculatePersistenceVarianceScale(float $phi): float
    {
        $boundedPhi = max(0.0, min(0.999999, $phi));

        return sqrt((1.0 - $boundedPhi) / (1.0 + $boundedPhi));
    }


    /**
     * Calculates a log-normal random draw, used for right-skewed distributions like M&A synergy.
     *
     * @param float $mu The mean of the underlying normal distribution.
     * @param float $sigma The standard deviation of the underlying normal distribution.
     * @return float A log-normal distributed value.
     */
    public function calculateLogNormalSynergy(float $mu, float $sigma): float
    {
        return exp($mu + $sigma * $this->generateStandardNormal());
    }

    /**
     * Generates a random draw from a standardized Student's t-distribution with unit variance.
     *
     * @param int $df Degrees of freedom (must be > 2 for defined variance).
     * @return float A standardized t-distributed random variable.
     */
    public function generateStudentsT(int $df = 4): float
    {
        $df = max(3, $df);
        $chiSquare = 0.0;
        for ($i = 0; $i < $df; $i++) {
            $z = $this->generateStandardNormal();
            $chiSquare += $z * $z;
        }

        // Guard the chi-square denominator. A draw of exactly zero has probability zero in continuous theory,
        // but is reachable in practice whenever the underlying normal generator is stubbed or seeded to a
        // constant, and the resulting division by zero would abort the whole simulation tick.
        $chiSquare = max($chiSquare, 1e-12);

        $rawT = $this->generateStandardNormal() / sqrt($chiSquare / $df);
        return $rawT * sqrt(($df - 2) / $df);
    }

    /**
     * Simulates the Merton Jump Diffusion process for sudden market shocks.
     * Returns the price multiplier and the raw components of the jump.
     *
     * @param float $lambda   The jump intensity (average number of jumps per year).
     * @param float $jumpMean The mean size of a jump (log-return).
     * @param float $jumpVol  The volatility of the jump size.
     * @param float $dt       The time step in years.
     * @return array{multiplier: float, shock_pct: float|null, exponent: float|null}
     */
    public function calculateJumpDiffusion(
        float $lambda,
        float $jumpMean,
        float $jumpVol,
        float $dt
    ): array {
        $jumpProb = $lambda * $dt;

        // Roll the dice to see if a jump occurs this tick
        if ($this->checkProbability($jumpProb)) {
            $jumpZ = $this->generateStandardNormal();

            $jumpExponent = $jumpMean + ($jumpVol * $jumpZ);
            $jumpMultiplier = exp($jumpExponent);
            $shockPct = ($jumpMultiplier - 1.0) * 100.0;

            return [
                'multiplier' => $jumpMultiplier,
                'shock_pct'  => $shockPct,
                'exponent'   => $jumpExponent
            ];
        }

        // No jump occurred
        return [
            'multiplier' => 1.0,
            'shock_pct'  => null,
            'exponent'   => null
        ];
    }

    /**
     * Calculates the next price using Geometric Brownian Motion (GBM) with correlated market drift.
     *
     * @param float $currentPrice      The current price of the stock.
     * @param float $currentVolatility The current instantaneous volatility.
     * @param float $drift             The expected return (drift) of the stock.
     * @param float $gravityDrift      The mean reversion drift pulling to fair value.
     * @param float $dt                The time step in years.
     * @param float $beta              The stock's beta (sensitivity to market movements).
     * @param float $marketVol         The volatility of the broader market.
     * @param float $marketZ           The systemic market shock Z-score.
     * @param float $w1                The idiosyncratic shock Z-score.
     * @param float $sectorZ           The shock Z-score common to this stock's macro sector.
     * @param float $sectorVarianceShare Fraction of NON-market variance loaded onto the sector factor.
     * @return float The new price calculated via GBM.
     */
    public function calculateCorrelatedGBM(
        float $currentPrice,
        float $currentVolatility,
        float $drift,
        float $gravityDrift,
        float $dt,
        float $beta,
        float $marketVol,
        float $marketZ,
        float $w1,
        float $sectorZ = 0.0,
        float $sectorVarianceShare = 0.0
    ): float {
        $impliedRho = $beta * ($marketVol / max($currentVolatility, 0.01));
        $marketCorrelation = max(-0.99, min(0.99, $impliedRho));

        // Orthogonal three-way variance decomposition: market, sector, idiosyncratic.
        // A single common factor makes two banks correlated only through their betas, so a sector rotation is
        // invisible in prices between earnings dates. Carving a share of the NON-market residual out for a
        // sector factor gives same-sector names a second shared driver: their correlation becomes
        // rho_market^2 + rho_sector^2 against rho_market^2 for a cross-sector pair. Loadings are square roots
        // of variance shares that sum to one, so total step variance stays exactly sigma^2 either way.
        $residualVariance = max(0.0, 1.0 - ($marketCorrelation * $marketCorrelation));
        $boundedShare = max(0.0, min(1.0, $sectorVarianceShare));
        $sectorLoading = sqrt($residualVariance * $boundedShare);
        $idiosyncraticLoading = sqrt($residualVariance * (1.0 - $boundedShare));

        $sqrtDt = sqrt($dt);
        $systematicDrift = $currentVolatility * $marketCorrelation * $marketZ * $sqrtDt;
        $sectorDrift = $currentVolatility * $sectorLoading * $sectorZ * $sqrtDt;
        $idiosyncraticDrift = $currentVolatility * $idiosyncraticLoading * $w1 * $sqrtDt;
        $currentVariance = $currentVolatility * $currentVolatility;

        $gbmExponent = ($drift + $gravityDrift - 0.5 * $currentVariance) * $dt
            + $systematicDrift + $sectorDrift + $idiosyncraticDrift;

        return $currentPrice * exp($gbmExponent);
    }

    /**
     * Calculates a step in the Cox-Ingersoll-Ross (CIR) process.
     * Used to model mean-reverting, strictly positive continuous processes (like operating margins).
     *
     * @param float $currentValue The current state variable.
     * @param float $kappa        The speed of mean reversion.
     * @param float $theta        The long-term structural target.
     * @param float $sigma        The volatility of the process.
     * @param float $dt           The time step delta.
     * @param float $dW           The Brownian motion Z-score.
     * @return float The next value in the process.
     */
    public function calculateCIR(float $currentValue, float $kappa, float $theta, float $sigma, float $dt, float $dW): float
    {
        $currentValue = max(0.0001, $currentValue);
        // Exact exponential discretization for mean-reversion drift prevents Euler overshooting when kappa * dt > 1.0
        $drift = ($theta - $currentValue) * (1.0 - exp(-$kappa * $dt));
        $diffusion = $sigma * sqrt($currentValue) * sqrt($dt) * $dW;

        return max(0.0001, $currentValue + $drift + $diffusion);
    }

    /**
     * Generates a random number from an Exponential distribution.
     *
     * @param float $rate The rate parameter (lambda) of the distribution.
     * @return float A random number drawn from the exponential distribution.
     */
    public function generateExponential(float $rate = 1.0): float
    {
        // Prevent log(0)
        $u = max($this->generateUniform(), 0.0000001);
        return -log($u) / $rate;
    }

    /**
     * Andersen's Quadratic-Exponential (QE) Discretization Scheme (2008).
     * Calculates the next variance state strictly positively, without bias.
     *
     * @param float $currentVar Current variance (Volatility squared).
     * @param float $theta      Long-term mean variance.
     * @param float $kappa      Reversion speed.
     * @param float $sigma      Volatility of volatility.
     * @param float $dt         Time step.
     * @return float The next strictly positive variance.
     */
    public function calculateQEVarianceStep(
        float $currentVar,
        float $theta,
        float $kappa,
        float $sigma,
        float $dt
    ): float {
        $expKappaDt = exp(-$kappa * $dt);

        // Calculate mean (m) and variance (s^2) of the next variance state
        $m = $theta + ($currentVar - $theta) * $expKappaDt;
        $s2 = ($currentVar * $sigma * $sigma * $expKappaDt / $kappa) * (1 - $expKappaDt)
            + ($theta * $sigma * $sigma / (2 * $kappa)) * pow(1 - $expKappaDt, 2);

        // Psi determines whether to use Quadratic or Exponential approximation
        // Clamped to a minimum of 1e-8 to prevent DivisionByZeroError if variance drops to absolute zero
        $psi = $m > 0 ? max($s2 / ($m * $m), 1e-8) : 2.0;

        $nextVar = 0.0;

        if ($psi <= 1.5) {
            // Non-central chi-square approximation (Quadratic)
            $b2 = 2 / $psi - 1 + sqrt((2 / $psi) * (2 / $psi - 1));
            $a = $m / (1 + $b2);
            $Zv = $this->generateStandardNormal();
            $nextVar = $a * pow(sqrt($b2) + $Zv, 2);
        } else {
            // Exponential approximation
            $p = ($psi - 1) / ($psi + 1);
            $beta = (1 - $p) / $m;
            $U = $this->generateUniform();

            if ($U > $p) {
                // Prevent log(0) if U is extremely close to 1
                $U = min($U, 0.9999999);
                $nextVar = (1 / $beta) * log((1 - $p) / (1 - $U));
            } else {
                $nextVar = 0.0;
            }
        }

        // Failsafe floor
        return max($nextVar, 0.0000001);
    }

    /**
     * SVJJ Model: Correlated Price and Variance Jumps using Kou Double-Exponential.
     *
     * @param float $lambda   Jump intensity (arrivals per year).
     * @param float $pUp      Probability that a jump is upwards (e.g., 0.3 for heavy left-tail).
     * @param float $etaUp    Rate of up-jump exponential decay.
     * @param float $etaDown  Rate of down-jump exponential decay.
     * @param float $muV      Mean of the variance jump (exponentially distributed).
     * @param float $dt       Time step.
     * @return array{price_multiplier: float, var_jump: float, shock_pct: float|null}
     */
    public function calculateSVJJJumps(
        float $lambda,
        float $pUp,
        float $etaUp,
        float $etaDown,
        float $muV,
        float $dt
    ): array {
        $jumpProb = $lambda * $dt;

        if ($this->checkProbability($jumpProb)) {
            // Price Jump (Kou Double-Exponential)
            $isUpJump = $this->generateUniform() < $pUp;

            if ($isUpJump) {
                $jumpSize = $this->generateExponential($etaUp);
                // Failsafe: Cap individual upside jumps to +20% (log(1.20) ≈ 0.1823)
                $jumpSize = min($jumpSize, FinancialConstants::MAX_JUMP_LOG_RETURN);
            } else {
                $jumpSize = -$this->generateExponential($etaDown);
                // Failsafe: Cap individual downside crashes to -20% (log(0.80) ≈ -0.2231)
                $jumpSize = max($jumpSize, FinancialConstants::MIN_JUMP_LOG_RETURN);
            }

            $priceMultiplier = exp($jumpSize);
            $shockPct = ($priceMultiplier - 1.0) * 100.0;

            // Variance Jump (Contemporaneous)
            // Market crashes usually spike volatility harder than market rallies
            $varianceJumpRate = $isUpJump ? (1.0 / ($muV * 0.5)) : (1.0 / $muV);
            $varJump = $this->generateExponential($varianceJumpRate);

            // Failsafe: Cap the variance jump to 10x the mean to prevent permanent volatility corruption
            $varJump = min($varJump, $muV * 10.0);

            return [
                'price_multiplier' => $priceMultiplier,
                'var_jump'         => $varJump,
                'shock_pct'        => $shockPct
            ];
        }

        return [
            'price_multiplier' => 1.0,
            'var_jump'         => 0.0,
            'shock_pct'        => null
        ];
    }

    /**
     * Applies a 1-Dimensional Kalman Filter to smooth Earnings Per Share (EPS).
     * Replaces arbitrary exponential decay heuristics with optimal statistical estimation.
     *
     * @param float $structuralEps    The prior estimate (Structural EPS derived from Book Value and ROIC).
     * @param float $quarterlyEps     The measurement (Actual Quarterly EPS print).
     * @param float $assetVolatility  The volatility of the firm's assets/equity (used to derive measurement noise).
     * @param float $macroUncertainty The level of macroeconomic stress (increases prior uncertainty).
     * @return float The posterior (smoothed) EPS estimate.
     */
    public function calculateKalmanSmoothedEps(float $structuralEps, float $quarterlyEps, float $assetVolatility, float $macroUncertainty): float
    {
        // 1. Process Noise (Uncertainty in our Structural Prior)
        // In stable times, we trust our structural ROIC. During macro stress (recessions), our prior is less reliable.
        $priorErrorCovariance = max(0.01, $macroUncertainty);

        // 2. Measurement Noise (Uncertainty in the Quarterly Print)
        // High-volatility companies (e.g., Tech startups) have very noisy quarterly earnings.
        // Low-volatility companies (e.g., Utilities) have stable prints.
        // We scale the variance based on asset volatility.
        $measurementVariance = max(0.01, $assetVolatility * 2.0);

        // 3. Kalman Gain
        // How much should we trust the new quarterly print vs our structural prior?
        // If Measurement Noise is huge, K approaches 0 (we ignore the print).
        // If Prior Uncertainty is huge, K approaches 1 (we blindly trust the new print).
        $kalmanGain = $priorErrorCovariance / ($priorErrorCovariance + $measurementVariance);

        // 4. Posterior Estimate
        // Update the structural prior with the new measurement, weighted by the Kalman Gain.
        $posteriorEps = $structuralEps + $kalmanGain * ($quarterlyEps - $structuralEps);

        return $posteriorEps;
    }

    /**
     * Calculates the Intrinsic Fair Value P/E ratio using fundamental drivers (Gordon Growth Model derivation).
     * P/E = (1 - Reinvestment Rate) / (Cost of Equity - Growth Rate)
     * Where Reinvestment Rate = Growth Rate / ROIC.
     *
     * @param float $costOfEquity The required rate of return for equity investors (Hurdle Rate).
     * @param float $roic         The Return on Invested Capital.
     * @param float $growthRate   The expected perpetual growth rate.
     * @return float The intrinsic fair value P/E multiple.
     */
    public function calculateIntrinsicFairValuePE(
        float $costOfEquity,
        float $roic,
        float $growthRate = FinancialConstants::DEFAULT_PERPETUAL_GROWTH_RATE
    ): float {
        // 1. Enforce absolute structural floor on Cost of Equity to prevent divergence under extreme distress
        $effectiveCostOfEquity = max(FinancialConstants::MIN_COST_OF_EQUITY, $costOfEquity);

        // 2. Enforce absolute structural bounds on perpetual growth rate [-5%, +6%]
        $clampedGrowth = max(FinancialConstants::MIN_PERPETUAL_GROWTH_RATE, min(FinancialConstants::MAX_PERPETUAL_GROWTH_RATE, $growthRate));

        // 3. In perpetual valuation, steady-state growth cannot exceed or equal the hurdle rate.
        // Constrain perpetual growth to at least 50 bps (0.005) below Cost of Equity to prevent divergence.
        $effectiveGrowth = min($clampedGrowth, $effectiveCostOfEquity - 0.005);

        // 4. Prevent division by zero or negative ROIC anomalies in perpetual calculations (floor at 0.01)
        $effectiveRoic = max(0.01, $roic);

        // 5. Reinvestment Rate = Growth / ROIC (bounded to [-1.0, 1.0] to prevent extreme negative payout distortions)
        $reinvestmentRate = max(-1.0, min(1.0, $effectiveGrowth / $effectiveRoic));

        $payoutRatio = 1.0 - $reinvestmentRate;

        // 6. Calculate Damodaran P/E multiple with safe spread denominator
        $spread = max(0.005, $effectiveCostOfEquity - $effectiveGrowth);
        $pe = $payoutRatio / $spread;

        // 7. Enforce structural market boundaries for distressed (4x) and superstar (35x) equities
        return max(FinancialConstants::MIN_INTRINSIC_PE, min(FinancialConstants::MAX_INTRINSIC_PE, $pe));
    }

    /**
     * Calculates the terminal value multiplier for a Discounted Cash Flow (DCF) using the Gordon Growth Model.
     *
     * @param float $wacc               The Weighted Average Cost of Capital.
     * @param float $terminalGrowthRate The expected perpetual growth rate.
     * @return float The DCF terminal multiplier.
     */
    public function calculateDcfMultiplier(
        float $wacc,
        float $terminalGrowthRate = FinancialConstants::DEFAULT_PERPETUAL_GROWTH_RATE
    ): float {
        $effectiveWacc = max(FinancialConstants::MIN_COST_OF_EQUITY, $wacc);
        $clampedGrowth = max(FinancialConstants::MIN_PERPETUAL_GROWTH_RATE, min(FinancialConstants::MAX_PERPETUAL_GROWTH_RATE, $terminalGrowthRate));
        $effectiveGrowth = min($clampedGrowth, $effectiveWacc - 0.005);

        $spread = max(0.005, $effectiveWacc - $effectiveGrowth);
        $multiplier = (1.0 + $effectiveGrowth) / $spread;

        return max(1.0, min(FinancialConstants::MAX_DCF_MULTIPLIER, $multiplier));
    }

    /**
     * Calculates Fair Value using the Dividend Discount Model (DDM).
     *
     * @param float $annualDividend The total dividend paid over the last 12 months.
     * @param float $discountRate   The required rate of return (Cost of Equity).
     * @param float $growthRate     The expected perpetual dividend growth rate.
     * @return float The intrinsic value of the stock based purely on its dividend stream.
     */
    public function calculateDividendDiscountModel(
        float $annualDividend,
        float $discountRate,
        float $growthRate = 0.01
    ): float {
        if ($annualDividend <= 0.0) {
            return 0.0;
        }

        $effectiveDiscountRate = max(FinancialConstants::MIN_COST_OF_EQUITY, $discountRate);
        $clampedGrowthRate = max(FinancialConstants::MIN_PERPETUAL_GROWTH_RATE, min(FinancialConstants::MAX_PERPETUAL_GROWTH_RATE, $growthRate));
        $effectiveGrowthRate = min($clampedGrowthRate, $effectiveDiscountRate - 0.005);

        // Prevent Division by Zero. The denominator must be at least 50 bps (0.005)
        $denominator = max(0.005, $effectiveDiscountRate - $effectiveGrowthRate);
        $multiplier = 1.0 / $denominator;

        $clampedMultiplier = min(FinancialConstants::MAX_DCF_MULTIPLIER, $multiplier);

        return $annualDividend * $clampedMultiplier;
    }

    /**
     * Calculates the yield for a given maturity using the Nelson-Siegel curve model.
     *
     * @param float $level     The long-term yield level.
     * @param float $slope     The short-term yield component.
     * @param float $curvature The medium-term hump component.
     * @param float $tau       The maturity in years (e.g., 10.0 for the 10-year yield).
     * @param float $lambda    The decay factor.
     * @return float The calculated yield for the specified maturity.
     */
    public function calculateNelsonSiegelYield(float $level, float $slope, float $curvature, float $tau, float $lambda = 0.5): float
    {
        if ($tau <= 0.0) {
            return $level + $slope;
        }

        $term1 = (1 - exp(-$lambda * $tau)) / ($lambda * $tau);
        $term2 = $term1 - exp(-$lambda * $tau);

        return $level + ($slope * $term1) + ($curvature * $term2);
    }

    /**
     * Calculates the yield for a given maturity using the Nelson-Siegel-Svensson (1994) curve model.
     * Extends Nelson-Siegel with a second curvature (hump) parameter to model more complex term structures.
     *
     * @param float $level      The long-term asymptotic yield level (beta0).
     * @param float $slope      The short-term yield component (beta1).
     * @param float $curvature1 The primary medium-term hump component (beta2).
     * @param float $curvature2 The secondary long-term hump component (beta3).
     * @param float $tau        The maturity in years (e.g., 10.0 for the 10-year yield).
     * @param float $lambda1    The first decay parameter governing the location of the primary hump.
     * @param float $lambda2    The second decay parameter governing the location of the secondary hump.
     * @return float The calculated yield for the specified maturity.
     */
    public function calculateSvenssonYield(
        float $level,
        float $slope,
        float $curvature1,
        float $curvature2,
        float $tau,
        float $lambda1 = 0.5,
        float $lambda2 = 0.15
    ): float {
        if ($tau <= 0.0) {
            return $level + $slope;
        }

        $term1 = (1.0 - exp(-$lambda1 * $tau)) / ($lambda1 * $tau);
        $term2 = $term1 - exp(-$lambda1 * $tau);

        $term3 = (1.0 - exp(-$lambda2 * $tau)) / ($lambda2 * $tau);
        $term4 = $term3 - exp(-$lambda2 * $tau);

        return $level + ($slope * $term1) + ($curvature1 * $term2) + ($curvature2 * $term4);
    }

    /**
     * Calculates an exponential distributed lag step (discrete recursive lag filter).
     * Models delayed transmission and economic stickiness (e.g., cost-push pass-through).
     *
     * @param float $currentLaggedValue The current lagged state variable.
     * @param float $targetValue        The new driving target value.
     * @param float $dt                 The time step in years.
     * @param float $lagTimeConstant    The characteristic adjustment time constant in years.
     * @return float The updated lagged value.
     */
    public function calculateDistributedLag(
        float $currentLaggedValue,
        float $targetValue,
        float $dt,
        float $lagTimeConstant
    ): float {
        if ($lagTimeConstant <= 0.0 || $dt <= 0.0) {
            return $targetValue;
        }

        $weight = 1.0 - exp(-$dt / $lagTimeConstant);
        return $currentLaggedValue + $weight * ($targetValue - $currentLaggedValue);
    }

    /**
     * Calculates the Weighted Average Cost of Capital (WACC).
     *
     * @param float $weightEquity The proportion of equity in the capital structure.
     * @param float $costOfEquity The required return on equity (CAPM).
     * @param float $weightDebt   The proportion of debt in the capital structure.
     * @param float $costOfDebt   The effective, post-tax cost of debt.
     * @return float The weighted average cost of capital.
     */
    public function calculateWACC(float $weightEquity, float $costOfEquity, float $weightDebt, float $costOfDebt): float
    {
        return ($weightEquity * $costOfEquity) + ($weightDebt * $costOfDebt);
    }

    /**
     * Calculates the Cost of Equity using the Capital Asset Pricing Model (CAPM).
     *
     * @param float $riskFreeRate      The baseline risk-free rate.
     * @param float $beta              The stock's levered beta.
     * @param float $equityRiskPremium The market equity risk premium.
     * @return float The expected return on equity.
     */
    public function calculateCAPM(float $riskFreeRate, float $beta, float $equityRiskPremium): float
    {
        return $riskFreeRate + ($beta * $equityRiskPremium);
    }

    /**
     * Levers a company's Beta using the Hamada equation.
     *
     * @param float $unleveredBeta The baseline asset beta.
     * @param float $taxRate       The corporate tax rate.
     * @param float $debtToEquity  The debt-to-equity ratio of the company.
     * @param float $dampening     A modifier to reduce double-counting if the baseline beta is already partially levered.
     * @return float The levered equity beta.
     */
    public function calculateLeveredBeta(float $unleveredBeta, float $taxRate, float $debtToEquity, float $dampening = 1.0): float
    {
        return $unleveredBeta * (1.0 + ((1.0 - $taxRate) * ($debtToEquity * $dampening)));
    }

    /**
     * Calculates the cumulative distribution function (CDF) for the standard normal distribution.
     * Uses a high-precision polynomial approximation.
     *
     * @param float $z The standard normal variable.
     * @return float The probability that a standard normal variable is less than or equal to $z.
     */
    public function calculateNormalCDF(float $z): float
    {
        $b1 = 0.319381530;
        $b2 = -0.356563782;
        $b3 = 1.781477937;
        $b4 = -1.821255978;
        $b5 = 1.330274429;
        $p  = 0.2316419;
        $c  = 0.39894228;

        if ($z >= 0.0) {
            $t = 1.0 / (1.0 + $p * $z);
            return (1.0 - $c * exp(-$z * $z / 2.0) * $t *
                ($t * ($t * ($t * ($t * $b5 + $b4) + $b3) + $b2) + $b1));
        } else {
            $t = 1.0 / (1.0 - $p * $z);
            return ($c * exp(-$z * $z / 2.0) * $t *
                ($t * ($t * ($t * ($t * $b5 + $b4) + $b3) + $b2) + $b1));
        }
    }

    /**
     * Calculates the inverse of the standard normal cumulative distribution function (Probit function).
     * Uses Peter J. Acklam's high-precision rational approximation (maximum error < 1.15e-9).
     *
     * @param float $p Probability value in (0, 1). Clamped to [1e-12, 1 - 1e-12] to prevent NaN/Inf.
     * @return float The standard normal quantile z corresponding to probability p.
     */
    public function calculateInverseNormalCDF(float $p): float
    {
        $p = max(1e-12, min(1.0 - 1e-12, $p));

        // Coefficients in rational approximations
        $a1 = -3.969683028665376e+01;
        $a2 =  2.209460984245205e+02;
        $a3 = -2.759285104469687e+02;
        $a4 =  1.383577518672690e+02;
        $a5 = -3.066479806614716e+01;
        $a6 =  2.506628277459239e+00;

        $b1 = -5.447609879822406e+01;
        $b2 =  1.615858368580409e+02;
        $b3 = -1.556989798598866e+02;
        $b4 =  6.680131188771972e+01;
        $b5 = -1.328068155288572e+01;

        $c1 = -7.784894002430293e-03;
        $c2 = -3.223964580411365e-01;
        $c3 = -2.400758277161838e+00;
        $c4 = -2.549732539343734e+00;
        $c5 =  4.374664141464968e+00;
        $c6 =  2.938163982698783e+00;

        $d1 =  7.784695709041462e-03;
        $d2 =  3.224671290700398e-01;
        $d3 =  2.445134137142996e+00;
        $d4 =  3.754408661907416e+00;

        $pLow  = 0.02425;
        $pHigh = 1.0 - $pLow;

        if ($p < $pLow) {
            // Rational approximation for lower tail
            $q = sqrt(-2.0 * log($p));
            return (((((($c1 * $q + $c2) * $q + $c3) * $q + $c4) * $q + $c5) * $q + $c6) /
                (((($d1 * $q + $d2) * $q + $d3) * $q + $d4) * $q + 1.0));
        }

        if ($p <= $pHigh) {
            // Rational approximation for central region
            $q = $p - 0.5;
            $r = $q * $q;
            return (((((($a1 * $r + $a2) * $r + $a3) * $r + $a4) * $r + $a5) * $r + $a6) * $q) /
                (((((($b1 * $r + $b2) * $r + $b3) * $r + $b4) * $r + $b5) * $r + 1.0));
        }

        // Rational approximation for upper tail
        $q = sqrt(-2.0 * log(1.0 - $p));
        return - (((((($c1 * $q + $c2) * $q + $c3) * $q + $c4) * $q + $c5) * $q + $c6) /
            (((($d1 * $q + $d2) * $q + $d3) * $q + $d4) * $q + 1.0));
    }

    /**
     * Calculates portfolio Expected Loss using the Basel II/III Asymptotic Single Risk Factor (ASRF) Vasicek model.
     *
     * Formula: PD(Z) = \Phi( (\Phi^{-1}(PD_LRA) - \sqrt{\rho} * Z) / \sqrt{1 - \rho} )
     *          EL(Z) = PD(Z) * LGD
     *
     * @param float $macroZ Macroeconomic credit shock Z-score (Z < 0 is recession/distress; Z > 0 is economic boom).
     * @param float $pdLra  Long-run average (through-the-cycle) probability of default.
     * @param float $rho    Asset correlation factor (\rho \in (0, 1)).
     * @param float $lgd    Loss given default (\in [0, 1]).
     * @return float Expected credit loss rate on the portfolio.
     */
    public function calculateVasicekExpectedLoss(float $macroZ, float $pdLra, float $rho, float $lgd): float
    {
        $pdLra = max(1e-6, min(0.999, $pdLra));
        $rho   = max(0.001, min(0.999, $rho));
        $lgd   = max(0.0, min(1.0, $lgd));

        $invPd = $this->calculateInverseNormalCDF($pdLra);
        $numerator = $invPd - (sqrt($rho) * $macroZ);
        $denominator = sqrt(1.0 - $rho);

        $conditionalPd = $this->calculateNormalCDF($numerator / $denominator);

        return $conditionalPd * $lgd;
    }

    /**
     * Calculates the Distance to Default (DD) using Merton's Structural Model.
     *
     * @param float $assetValue      The total value of the firm's assets (V).
     * @param float $debtFaceValue   The face value of the firm's debt (D).
     * @param float $assetVolatility The volatility of the firm's assets (sigma_V).
     * @param float $riskFreeRate    The risk-free rate (r).
     * @param float $timeToMaturity  The time to maturity of the debt in years (T).
     * @return float The Distance to Default in standard deviations.
     */
    public function calculateDistanceToDefault(float $assetValue, float $debtFaceValue, float $assetVolatility, float $riskFreeRate, float $timeToMaturity = 1.0): float
    {
        if ($debtFaceValue <= 0.0 || $assetValue <= 0.0 || $assetVolatility <= 0.0 || $timeToMaturity <= 0.0) {
            return 10.0; // Effectively no default risk
        }

        $d1 = (log($assetValue / $debtFaceValue) + ($riskFreeRate + 0.5 * pow($assetVolatility, 2.0)) * $timeToMaturity)
            / ($assetVolatility * sqrt($timeToMaturity));

        // In the Merton model, the actual Distance to Default is d2
        $d2 = $d1 - ($assetVolatility * sqrt($timeToMaturity));

        return $d2;
    }

    /**
     * Calculates the theoretical credit spread based on Merton's Structural Model.
     *
     * @param float $distanceToDefault The distance to default (d2).
     * @param float $lossGivenDefault  The expected loss percentage if default occurs (LGD).
     * @param float $timeToMaturity    The time to maturity of the debt in years (T).
     * @return float The theoretical credit spread in decimal (e.g. 0.02 for 2%).
     */
    public function calculateMertonCreditSpread(float $distanceToDefault, float $lossGivenDefault = 0.40, float $timeToMaturity = 1.0): float
    {
        // Probability of Default (PD) is N(-DD)
        $probabilityOfDefault = $this->calculateNormalCDF(-$distanceToDefault);

        // Failsafe: Cap PD slightly below 1.0 to prevent log(0) in the spread formula
        $probabilityOfDefault = min(0.9999, $probabilityOfDefault);

        $spread = - (1.0 / $timeToMaturity) * log(1.0 - ($probabilityOfDefault * $lossGivenDefault));

        // Failsafe: Prevent negative spreads or astronomical blowout
        return max(0.0, min(1.0, $spread)); // Max spread capped at 10,000 bps
    }
    /**
     * Calculates a step in the Schwartz 1-Factor Model (1997) for commodity pricing.
     * Uses an Ornstein-Uhlenbeck (OU) process on the natural logarithm of the price,
     * ensuring strictly positive, right-skewed log-normal distributions.
     *
     * @param float $currentPrice The current commodity price (S).
     * @param float $kappa        The speed of mean reversion.
     * @param float $theta        The long-term equilibrium price level.
     * @param float $sigma        The volatility of the log price.
     * @param float $dt           The time step delta.
     * @param float $dW           The Brownian motion Z-score.
     * @return float The next commodity price.
     */
    public function calculateSchwartz1Factor(float $currentPrice, float $kappa, float $theta, float $sigma, float $dt, float $dW): float
    {
        $currentPrice = max(0.0001, $currentPrice);
        $currentLogPrice = log($currentPrice);

        // The long term mean of the log-price needs an Ito correction to match the expected level of the spot price
        $alpha = log($theta) - ($sigma * $sigma) / (2.0 * max(0.0001, $kappa));

        // Exact solution for OU process to prevent Euler discretization errors for large kappa * dt
        $expKappaDt = exp(-$kappa * $dt);
        $drift = $currentLogPrice * $expKappaDt + $alpha * (1.0 - $expKappaDt);

        // The exact variance of the OU process over dt
        $variance = ($sigma * $sigma / (2.0 * max(0.0001, $kappa))) * (1.0 - exp(-2.0 * $kappa * $dt));
        $diffusion = sqrt($variance) * $dW;

        $nextLogPrice = $drift + $diffusion;

        return exp($nextLogPrice);
    }

    /**
     * Schwartz-Smith 2-Factor Model (2000) for industrial commodity pricing.
     * Decomposes log-price into a mean-reverting short-term deviation (chi)
     * and a drifting long-term equilibrium (xi).
     *
     * @param float $chi     Current short-term log-deviation state.
     * @param float $xi      Current long-term log-equilibrium state.
     * @param float $kappa   Mean-reversion speed of short-term deviation.
     * @param float $muXi    Drift rate of long-term equilibrium (supercycle trend).
     * @param float $sigChi  Volatility of short-term deviation.
     * @param float $sigXi   Volatility of long-term equilibrium.
     * @param float $rho     Correlation between chi and xi innovations.
     * @param float $dt      Time step in years.
     * @param float|null $dW1 Optional standard normal draw for short-term factor.
     * @param float|null $dW2 Optional standard normal draw for long-term factor uncorrected component.
     * @return array{chi: float, xi: float, spot: float}
     */
    public function calculateSchwartz2Factor(
        float $chi,
        float $xi,
        float $kappa,
        float $muXi,
        float $sigChi,
        float $sigXi,
        float $rho,
        float $dt,
        ?float $dW1 = null,
        ?float $dW2 = null
    ): array {
        $dW1 ??= $this->generateStandardNormal();
        $dW2 ??= $this->generateStandardNormal();

        $clampedRho = max(-0.99, min(0.99, $rho));
        $safeKappa = max(0.0001, $kappa);

        // Correlated standard normal innovations
        $zChi = $dW1;
        $zXi = ($clampedRho * $dW1) + (sqrt(1.0 - ($clampedRho * $clampedRho)) * $dW2);

        // Exact discretization of OU process for chi (mean-reverting to 0)
        $expKappaDt = exp(-$safeKappa * $dt);
        $chiDrift = $chi * $expKappaDt;
        $chiVariance = ($sigChi * $sigChi / (2.0 * $safeKappa)) * (1.0 - exp(-2.0 * $safeKappa * $dt));
        $nextChi = $chiDrift + sqrt($chiVariance) * $zChi;

        // Long-term equilibrium drift (Arithmetic Brownian Motion for log-equilibrium)
        $nextXi = $xi + ($muXi * $dt) + ($sigXi * sqrt($dt) * $zXi);

        $spot = exp($nextChi + $nextXi);

        return [
            'chi'  => $nextChi,
            'xi'   => $nextXi,
            'spot' => $spot,
        ];
    }

    /**
     * Two-Factor Correlated Ornstein-Uhlenbeck (OU) Process.
     * Models a spot price derived from two distinct mean-reverting log-state variables.
     * Ideal for bounded index simulations (e.g., short-term shocks vs long-term structural cycles).
     *
     * @param float $chi       Current state of Factor 1 (e.g., short-term).
     * @param float $xi        Current state of Factor 2 (e.g., long-term).
     * @param float $kappaChi  Mean-reversion speed of Factor 1.
     * @param float $kappaXi   Mean-reversion speed of Factor 2.
     * @param float $thetaChi  Equilibrium target of Factor 1.
     * @param float $thetaXi   Equilibrium target of Factor 2.
     * @param float $sigChi    Volatility of Factor 1.
     * @param float $sigXi     Volatility of Factor 2.
     * @param float $rho       Correlation coefficient between the two factors [-1, 1].
     * @param float $dt        Time step in years.
     * @param float|null $dW1  Optional standard normal draw for Factor 1.
     * @param float|null $dW2  Optional standard normal draw for Factor 2.
     * @return array{chi: float, xi: float, spot: float}
     */
    public function calculateTwoFactorOU(
        float $chi,
        float $xi,
        float $kappaChi,
        float $kappaXi,
        float $thetaChi,
        float $thetaXi,
        float $sigChi,
        float $sigXi,
        float $rho,
        float $dt,
        ?float $dW1 = null,
        ?float $dW2 = null
    ): array {
        $dW1 ??= $this->generateStandardNormal();
        $dW2 ??= $this->generateStandardNormal();

        $clampedRho = max(-0.99, min(0.99, $rho));
        $safeKappaChi = max(0.0001, $kappaChi);
        $safeKappaXi = max(0.0001, $kappaXi);

        // Correlated standard normal innovations
        $zChi = $dW1;
        $zXi = ($clampedRho * $dW1) + (sqrt(1.0 - ($clampedRho * $clampedRho)) * $dW2);

        // Exact discretization for Factor 1 (Chi)
        $expKappaChiDt = exp(-$safeKappaChi * $dt);
        $chiDrift = ($chi * $expKappaChiDt) + ($thetaChi * (1.0 - $expKappaChiDt));
        $chiVariance = ($sigChi * $sigChi / (2.0 * $safeKappaChi)) * (1.0 - exp(-2.0 * $safeKappaChi * $dt));
        $nextChi = $chiDrift + sqrt($chiVariance) * $zChi;

        // Exact discretization for Factor 2 (Xi)
        $expKappaXiDt = exp(-$safeKappaXi * $dt);
        $xiDrift = ($xi * $expKappaXiDt) + ($thetaXi * (1.0 - $expKappaXiDt));
        $xiVariance = ($sigXi * $sigXi / (2.0 * $safeKappaXi)) * (1.0 - exp(-2.0 * $safeKappaXi * $dt));
        $nextXi = $xiDrift + sqrt($xiVariance) * $zXi;

        $spot = exp($nextChi + $nextXi);

        return [
            'chi'  => $nextChi,
            'xi'   => $nextXi,
            'spot' => $spot,
        ];
    }

    public function calculateReversionPull(
        float $currentReturn,
        float $wacc,
        float $baseKappa,
        float $moatSpread,
        float $dt = 0.25,
        float $erosionAlpha = 0.50,
        float $distressPersistence = 0.60,
        float $distressGamma = 1.00
    ): float {
        $equilibrium = $wacc + $moatSpread;

        $safeEquilibriumDivisor = max(0.01, abs($equilibrium));

        if ($currentReturn > $equilibrium) {
            $excessRatio = ($currentReturn - $equilibrium) / $safeEquilibriumDivisor;
            $effectiveKappa = $baseKappa * (1.0 + $erosionAlpha * $excessRatio);
        } elseif ($currentReturn < 0.0) {
            $distressRatio = abs($currentReturn) / max(0.01, $wacc);
            $effectiveKappa = $baseKappa * $distressPersistence * (1.0 + $distressGamma * $distressRatio);
        } else {
            $effectiveKappa = $baseKappa * $distressPersistence;
        }

        // EXACT DISCRETIZATION: Use the exponential solution (1 - e^(-kappa * dt))
        // This acts as a dampener. Even if effectiveKappa approaches infinity, 
        // the weight naturally caps at 1.0, mathematically preventing target overshooting.
        $reversionWeight = 1.0 - exp(-$effectiveKappa * $dt);

        return ($equilibrium - $currentReturn) * $reversionWeight;
    }

    /**
     * Calculates the Earnings Response Coefficient (ERC) based on empirical models.
     * The ERC determines how strongly a stock price reacts to an earnings surprise.
     * 
     * @param float $sue           Standardized Unexpected Earnings (Surprise %).
     * @param float $beta          The stock's levered beta (risk).
     * @param float $growthPremium The valuation premium or growth expectations.
     * @return float The price drift percentage resulting from the earnings surprise.
     */
    public function calculateEarningsResponseCoefficient(float $sue, float $beta, float $growthPremium): float
    {
        // High beta (risk) means more noise, reducing the ERC
        // High growth premium implies higher persistence of earnings, increasing the ERC
        $ercBeta = max(0.1, 1.0 + (FinancialConstants::ERC_BETA_SENSITIVITY * $beta) + (FinancialConstants::ERC_GROWTH_SENSITIVITY * $growthPremium));

        return FinancialConstants::ERC_BASE_ALPHA + ($ercBeta * $sue);
    }

    /**
     * Updates analyst consensus using a Bayesian Inference Model.
     * 
     * @param float $priorEstimate  The previous analyst consensus estimate.
     * @param float $priorVariance  The uncertainty (variance) of the prior estimate.
     * @param float $newSignal      The new fundamental signal (e.g., actual structural revenue).
     * @param float $signalVariance The uncertainty (variance) of the new signal.
     * @return float The posterior (updated) analyst consensus.
     */
    public function calculateBayesianAnalystUpdate(float $priorEstimate, float $priorVariance, float $newSignal, float $signalVariance): float
    {
        // Prevent division by zero
        $priorPrecision = 1.0 / max(0.0001, $priorVariance);
        $signalPrecision = 1.0 / max(0.0001, $signalVariance);

        // Posterior is the precision-weighted average of the prior and the new signal
        $posteriorEstimate = (($priorEstimate * $priorPrecision) + ($newSignal * $signalPrecision)) / ($priorPrecision + $signalPrecision);

        return $posteriorEstimate;
    }

    /**
     * Calculates the mean-reverting exponential moving average (Ornstein-Uhlenbeck mix drift) for dynamic portfolio/revenue weights.
     *
     * Formula: w_{t+1} = w_t + alpha * (realized_t - w_t) + kappa * (target - w_t)
     *
     * @param float $currentWeight Current active weight w_t
     * @param float $realizedShare Recent realized share r_t
     * @param float $targetWeight  Long-term strategic anchor theta
     * @param float $alpha         Adaptation speed parameter [0, 1]
     * @param float $kappa         Mean reversion pull speed [0, 1]
     * @param float $minFloor      Minimum structural floor clamp for active diversified segments
     * @param float $maxCeiling    Maximum structural ceiling clamp for diversified segments
     * @return float Clamped updated weight before simplex normalization
     */
    public function calculateMeanRevertingWeight(
        float $currentWeight,
        float $realizedShare,
        float $targetWeight,
        float $alpha,
        float $kappa,
        float $minFloor = FinancialConstants::DEFAULT_MIN_STREAM_WEIGHT_FLOOR,
        float $maxCeiling = FinancialConstants::DEFAULT_MAX_STREAM_WEIGHT_CEILING
    ): float {
        $drift = $alpha * ($realizedShare - $currentWeight);
        $reversion = $kappa * ($targetWeight - $currentWeight);
        $raw = $currentWeight + $drift + $reversion;

        $effectiveMinFloor = $targetWeight <= 0.0 ? 0.0 : min($minFloor, $targetWeight);
        $effectiveMaxCeiling = max($maxCeiling, $targetWeight);

        return max($effectiveMinFloor, min($effectiveMaxCeiling, $raw));
    }

    /**
     * Normalizes an array of weights to sum strictly to 1.0 (simplex projection).
     * Clamps weights to non-negative values to ensure valid probability simplex.
     *
     * @param array<string, float> $weights
     * @return array<string, float>
     */
    public function normalizeWeightsSimplex(array $weights): array
    {
        $clamped = array_map(fn($w) => max(0.0, (float) $w), $weights);
        $total = array_sum($clamped);
        if ($total <= 0.0) {
            $count = count($clamped);
            $equal = $count > 0 ? 1.0 / $count : 1.0;
            return array_map(fn() => $equal, $clamped);
        }

        $normalized = [];
        foreach ($clamped as $key => $weight) {
            $normalized[$key] = $weight / $total;
        }

        return $normalized;
    }

    /**
     * Calculates a convex penalty using power-law scaling to model non-linear demand destruction,
     * bullwhip supply chain freezes, or aggressive promotional inventory markdowns.
     *
     * Formula: Penalty = (max(0, Shock))^Convexity * Scalar
     *
     * @param float $shock     The magnitude of the shock/contraction (e.g. abs(outputGap)).
     * @param float $convexity The degree of convexity (e.g. 1.5 or 2.0).
     * @param float $scalar    The scaling factor.
     * @return float The non-linear convex penalty.
     */
    public function calculateConvexPenalty(float $shock, float $convexity = 1.5, float $scalar = 1.0): float
    {
        if ($shock <= 0.0) {
            return 0.0;
        }

        return pow($shock, $convexity) * $scalar;
    }

    /**
     * Models Asymmetric Cost Stickiness (Anderson, Banker, & Janakiraman 2003).
     *
     * Operating costs drop sluggishly when revenue contracts due to fixed commitments,
     * employee retention frictions, and severance liabilities, causing operating margins
     * to compress sharply during revenue declines.
     *
     * @param float $currentVariableMargin The baseline variable cost ratio (Costs / Revenue).
     * @param float $revenueLogChange       Quarter-over-quarter log change in revenue: ln(Rev_t / Rev_{t-1}).
     * @param float $betaExpansion          Cost elasticity on revenue growth (beta 1).
     * @param float $betaContractionPenalty Downward stickiness penalty parameter (beta 2 < 0).
     * @return float The adjusted realized variable cost ratio (Costs / Revenue).
     */
    public function calculateAsymmetricCostStickiness(
        float $currentVariableMargin,
        float $revenueLogChange,
        float $betaExpansion = FinancialConstants::STICKY_COST_BETA_EXPANSION,
        float $betaContractionPenalty = FinancialConstants::STICKY_COST_BETA_CONTRACTION_PENALTY
    ): float {
        // Delta ln(Cost) = beta1 * Delta ln(Rev) + beta2 * I(Delta ln(Rev) < 0) * Delta ln(Rev)
        $isContraction = $revenueLogChange < 0.0 ? 1.0 : 0.0;
        $costElasticity = $betaExpansion + ($betaContractionPenalty * $isContraction);

        // Margin shift: ln(Cost_t / Rev_t) - ln(Cost_{t-1} / Rev_{t-1}) = (costElasticity - 1.0) * Delta ln(Rev)
        $logMarginMultiplier = ($costElasticity - 1.0) * $revenueLogChange;
        $adjustedMargin = $currentVariableMargin * exp($logMarginMultiplier);

        return max(FinancialConstants::MIN_VARIABLE_MARGIN_CLAMP, min(FinancialConstants::MAX_VARIABLE_MARGIN_CLAMP, $adjustedMargin));
    }

    /**
     * Computes the dynamic Cash Conversion Cycle (CCC) strain on working capital intensity.
     *
     * During downturns:
     * - DSO expands as customers delay payments (credit spread stress).
     * - DIO expands as unsold inventories accumulate (low capacity utilization).
     * - DPO contracts as vendors demand accelerated payment (interbank funding liquidity stress).
     *
     * @param float $baselineIntensity         The baseline working capital intensity (NWC / Revenue).
     * @param float $creditSpread              Prevailing corporate credit spread (DSO driver).
     * @param float $capacityUtilization       Current operating capacity utilization ratio (DIO driver).
     * @param float $interbankLiquiditySpread  Prevailing interbank liquidity funding spread (DPO driver).
     * @return float The dynamic working capital intensity for the quarter.
     */
    public function calculateDynamicWorkingCapitalIntensity(
        float $baselineIntensity,
        float $creditSpread,
        float $capacityUtilization,
        float $interbankLiquiditySpread
    ): float {
        // Dynamic shifts in Days Sales Outstanding (DSO), Days Inventory Outstanding (DIO), and Days Payable Outstanding (DPO)
        $dsoShiftDays = ($creditSpread - MacroEngine::BASE_CREDIT_SPREAD) * FinancialConstants::CCC_DSO_CREDIT_SPREAD_SENSITIVITY;
        $dioShiftDays = (1.0 - $capacityUtilization) * FinancialConstants::CCC_DIO_CAPACITY_SENSITIVITY;
        // Under interbank liquidity stress, vendors demand faster payment (DPO contracts)
        $dpoShiftDays = - ($interbankLiquiditySpread - MacroEngine::INTERBANK_BASELINE_SPREAD) * FinancialConstants::CCC_DPO_LIQUIDITY_SENSITIVITY;

        // Total CCC expansion / contraction days translated to annual intensity units (Days / 365)
        // Standard formula: CCC = DSO + DIO - DPO
        // Therefore: Delta CCC = Delta DSO + Delta DIO - Delta DPO
        $totalCccShiftDays = $dsoShiftDays + $dioShiftDays - $dpoShiftDays;
        $intensityShift = $totalCccShiftDays / 365.0;

        $dynamicIntensity = $baselineIntensity + $intensityShift;

        if ($baselineIntensity < 0.0) {
            // Negative working capital (float): Under CCC expansion / liquidity stress, vendors tighten terms,
            // compressing the negative float toward zero (clamped between MIN_NEGATIVE_NWC_INTENSITY and MAX_NEGATIVE_NWC_INTENSITY).
            return min(FinancialConstants::MAX_NEGATIVE_NWC_INTENSITY, max(FinancialConstants::MIN_NEGATIVE_NWC_INTENSITY, $dynamicIntensity));
        }

        return max(FinancialConstants::MIN_POSITIVE_NWC_INTENSITY, min(FinancialConstants::MAX_POSITIVE_NWC_INTENSITY, $dynamicIntensity));
    }

    /**
     * Calculates the non-linear capacity-constrained output gap effect on inflation
     * using the Benigno & Eggertsson (2023) / Harding, Lindé, & Trabandt (2022) convex Phillips curve.
     *
     * During economic expansions, as output gap y approaches structural capacity ceiling y_max, supply bottlenecks
     * bind asymptotically, causing non-linear inflation acceleration. During contractions (y < 0),
     * downward nominal wage and price rigidity flattens the curve toward a sticky minimum slope.
     *
     * Formula:
     *   For y >= 0: f(y) = kappa * (y / max(0.001, y_max - y))
     *   For y < 0:  f(y) = kappa * downwardRigidityFactor * y
     *
     * @param float $outputGap              Current macroeconomic output gap (e.g., 0.02 for +2%).
     * @param float $maxCapacity            Asymptotic output gap ceiling where capacity binds (e.g., 0.08).
     * @param float $kappa                  Baseline slope sensitivity parameter.
     * @param float $downwardRigidityFactor Downward nominal rigidity slope multiplier (0 < factor < 1).
     * @return float Non-linear demand-pull Phillips curve inflation pressure.
     */
    public function calculateConvexPhillipsCurve(
        float $outputGap,
        float $maxCapacity = 0.08,
        float $kappa = 0.020,
        float $downwardRigidityFactor = 0.35
    ): float {
        if ($outputGap >= 0.0) {
            $effectiveCeiling = max(0.005, $maxCapacity - $outputGap);
            return $kappa * ($outputGap / $effectiveCeiling);
        }

        $baseSlope = $maxCapacity > 0 ? ($kappa / $maxCapacity) : 0.25;
        return $baseSlope * $downwardRigidityFactor * $outputGap;
    }

    /**
     * Calculates the duration-weighted preferred-habitat term premium shift under QE/QT (Vayanos & Vila 2021).
     *
     * When the central bank expands its balance sheet via Quantitative Easing (QE), it extracts net duration
     * from the market, reducing the duration risk absorbed by private arbitrageurs and compressing term premia.
     * The effect scales proportionally with bond maturity/tenor duration.
     *
     * Formula: Delta TP(tau) = - lambda_habitat * (tau / 10.0) * balanceSheetIntensity
     *
     * @param float $balanceSheetIntensity Positive for QE (yield suppression), negative for QT (steepening).
     * @param float $tau                   Bond tenor maturity in years (e.g. 2.0, 5.0, 10.0, 30.0).
     * @param float $habitatSensitivity    Sensitivity parameter scaling duration extraction.
     * @return float Term premium shift in decimal (e.g., -0.0050 for -50bps).
     */
    public function calculatePreferredHabitatTermPremiumShift(
        float $balanceSheetIntensity,
        float $tau,
        float $habitatSensitivity = 1.0
    ): float {
        $durationWeight = $tau / 10.0;
        return -$balanceSheetIntensity * $durationWeight * $habitatSensitivity;
    }

    /**
     * Calculates Investment Grade (IG) and High Yield (HY) corporate credit spreads
     * incorporating the Jarrow, Lando, & Turnbull (1997) rating migration model and "fallen angel" cliff.
     *
     * During severe macroeconomic contractions, corporate credit rating transitions migrate toward speculative
     * grades, where institutional investment mandates trigger forced selling, exponentially blowing out HY spreads.
     *
     * @param float $baseIgSpread     Baseline investment-grade spread (e.g. 0.020).
     * @param float $outputGapEma     Smoothed macroeconomic output gap.
     * @param float $marketVolEma     Smoothed equity market volatility.
     * @param float $interbankStress  Wholesale interbank liquidity stress above baseline.
     * @param float $hyBaseMultiplier Baseline multiple of HY spread over IG spread (e.g. 2.4x).
     * @param float $fallenAngelSens  Sensitivity coefficient for non-linear HY spread blowout on contractions.
     * @return array{ig: float, hy: float} Calculated IG and HY credit spreads.
     */
    public function calculateDualTrancheCreditSpreads(
        float $baseIgSpread,
        float $outputGapEma,
        float $marketVolEma,
        float $interbankStress,
        float $hyBaseMultiplier = 2.4,
        float $fallenAngelSens = 8.0
    ): array {
        $cycleSpread = $baseIgSpread * exp(-2.5 * $outputGapEma);
        $excessVol = max(0.0, $marketVolEma - 0.20);
        $volSpread = 0.15 * $excessVol;
        $contagionSpread = $interbankStress * 2.0;

        $igSpread = max(0.008, min(0.10, $cycleSpread + $volSpread + $contagionSpread));

        // Jarrow-Lando-Turnbull (1997): Speculative-grade default intensity surges exponentially during recessions
        $contractionDepth = max(0.0, -$outputGapEma);
        $fallenAngelMultiplier = exp($fallenAngelSens * $contractionDepth);
        $hySpread = max($igSpread * 1.5, min(0.25, $igSpread * $hyBaseMultiplier * $fallenAngelMultiplier));

        return [
            'ig' => $igSpread,
            'hy' => $hySpread,
        ];
    }

    /**
     * Models the Metzler (1941) & Blinder (1982) macroeconomic inventory investment cycle.
     *
     * Evaluates inventory stock acceleration: when aggregate demand decelerates, involuntary inventory
     * accumulation occurs (+gap). In response, firms cut production below sales to aggressively liquidate stock,
     * driving industrial recessions. Once depleted (-gap), the restocking rebound accelerates output recovery.
     *
     * @param float $currentInventoryGap Current inventory overhang (+gap is excess stock, -gap is depleted).
     * @param float $outputGap           Current output gap level.
     * @param float $outputGapEma        Smoothed output gap trend.
     * @param float $speed               Annual speed of inventory adjustment toward desired ratio.
     * @param float $surpriseSens        Sensitivity of involuntary inventory build to growth slowdown.
     * @param float $dt                  Time step in years.
     * @return float Updated inventory gap bounded between -0.15 and +0.15.
     */
    public function calculateInventoryCycleStep(
        float $currentInventoryGap,
        float $outputGap,
        float $outputGapEma,
        float $speed,
        float $surpriseSens,
        float $dt,
        float $cyclicalSens = 0.80
    ): float {
        // Involuntary inventory change driven by unexpected demand deceleration
        $demandDeceleration = $outputGapEma - $outputGap;
        $involuntaryFlow = $surpriseSens * $demandDeceleration;

        // Cyclical stock target: contractions cause inventory-to-sales ratios to spike (overhang),
        // while expansions lean out inventories (depletion).
        $cyclicalTarget = -$cyclicalSens * $outputGap;

        // Desired inventory correction: firms adjust production toward cyclical target
        $targetCorrection = -$speed * ($currentInventoryGap - $cyclicalTarget);

        $dInventory = ($involuntaryFlow + $targetCorrection) * $dt;
        $newInventoryGap = $currentInventoryGap + $dInventory;

        return max(-0.15, min(0.15, $newInventoryGap));
    }

    /**
     * Calculates the non-linear convenience yield under the Theory of Storage (Working 1949, Litzenberger & Rabinowitz 1995).
     *
     * When physical inventory levels are ample (above baseline), the market is in contango and convenience yield is near zero.
     * When physical inventories drop toward a critical buffer threshold, convenience yield spikes asymptotically,
     * inducing extreme spot price inelasticity and backwardation.
     *
     * @param float $inventoryLevel Normalized inventory index (100 = neutral, < 80 = tight, < 55 = critical).
     * @param float $minBufferStock Critical structural minimum buffer stock floor.
     * @param float $yieldScale     Scaling multiplier.
     * @param float $exponent       Asymptotic curvature exponent.
     * @return float Annualized convenience yield percentage add-on.
     */
    public function calculateConvenienceYield(
        float $inventoryLevel,
        float $minBufferStock = 50.0,
        float $yieldScale = 0.10,
        float $exponent = 1.8
    ): float {
        $bufferSlack = max(1.0, $inventoryLevel - $minBufferStock);
        $neutralSlack = max(1.0, 100.0 - $minBufferStock);

        if ($inventoryLevel >= 100.0) {
            // Contango regime: convenience yield negligible
            return 0.0;
        }

        // Backwardation regime: convenience yield rises non-linearly as inventories deplete
        $tightnessRatio = $neutralSlack / $bufferSlack;
        return $yieldScale * (pow($tightnessRatio, $exponent) - 1.0);
    }

    /**
     * Calculates the 12-month forward recession probability using the Estrella & Mishkin (1998) probit model.
     *
     * Evaluates market-implied recession probability based on yield curve slope (10Y minus policy rate),
     * term premium, and the Financial Conditions Index:
     *   P(Recession) = NormalCDF(beta0 + betaSlope * slope + betaTp * termPremium + betaFci * FCI)
     *
     * @param float $slope       Yield curve slope (Yield10Y minus policy rate).
     * @param float $termPremium Sovereign 10Y term premium.
     * @param float $fci         Financial Conditions Index (FCI > 0 is restrictive).
     * @param float $beta0       Probit intercept parameter (calibrated to ~15% baseline probability at neutral slope).
     * @param float $betaSlope   Sensitivity to yield curve slope.
     * @param float $betaTp      Sensitivity to term premium compression.
     * @param float $betaFci     Sensitivity to financial conditions tightening.
     * @return float 12-month forward recession probability clamped between 1% and 99%.
     */
    public function calculateEstrellaMishkinProbability(
        float $slope,
        float $termPremium,
        float $fci,
        float $beta0 = -0.55,
        float $betaSlope = -80.0,
        float $betaTp = -20.0,
        float $betaFci = 0.35
    ): float {
        $probitIndex = $beta0 + ($betaSlope * $slope) + ($betaTp * $termPremium) + ($betaFci * $fci);
        $probability = $this->calculateNormalCDF($probitIndex);
        return max(0.01, min(0.99, $probability));
    }

    /**
     * Calculates the Federal Reserve G.17 Industrial Capacity Utilization Rate.
     *
     * Models real physical factory and equipment load factor based on the macroeconomic output gap
     * and physical capital stock overhang:
     *   CU = baselineCu + gapSens * outputGap - overhangSens * capitalStockOverhang
     *
     * @param float $outputGap              Macroeconomic output gap.
     * @param float $capitalStockOverhang   Accumulated capital stock overhang.
     * @param float $baselineCu             Historical neutral capacity utilization (~78.5%).
     * @param float $gapSensitivity         Sensitivity to cyclical demand fluctuations.
     * @param float $overhangSensitivity    Sensitivity to excess installed capacity overhang.
     * @return float Realized capacity utilization rate clamped between 60% and 92%.
     */
    public function calculateCapacityUtilization(
        float $outputGap,
        float $capitalStockOverhang,
        float $baselineCu = 0.785,
        float $gapSensitivity = 0.85,
        float $overhangSensitivity = 0.40
    ): float {
        $rawCu = $baselineCu + ($gapSensitivity * $outputGap) - ($overhangSensitivity * $capitalStockOverhang);
        return max(0.60, min(0.92, $rawCu));
    }

    /**
     * Calculates the aggregate speculative-grade corporate default rate (Moody's / S&P Speculative Default Model).
     *
     * Derives realized corporate defaults via the Merton/Vasicek structural credit portfolio transition:
     *   CDR = NormalCDF( (InverseNormalCDF(baseDefault) - sqrt(rho) * macroZ) / sqrt(1 - rho) )
     *
     * @param float $macroZ          Composite macroeconomic credit Z-score.
     * @param float $baseDefaultRate Long-run average speculative corporate default rate (~1.8%).
     * @param float $rho             Corporate asset correlation factor (~20% under Basel II/III).
     * @return float Realized annual corporate default rate clamped between 0.2% and 18%.
     */
    public function calculateCorporateDefaultRate(
        float $macroZ,
        float $baseDefaultRate = 0.018,
        float $rho = 0.20
    ): float {
        $invPd = $this->calculateInverseNormalCDF($baseDefaultRate);
        $sqrtRho = sqrt($rho);
        $numerator = $invPd - ($sqrtRho * $macroZ);
        $denominator = sqrt(1.0 - $rho);
        $conditionalPd = $this->calculateNormalCDF($numerator / $denominator);

        return max(0.002, min(0.18, $conditionalPd));
    }

    /**
     * Models the Federal Reserve Senior Loan Officer Opinion Survey (SLOOS) Credit Standards Index.
     *
     * Evaluates the net percentage of domestic commercial banks tightening lending standards for C&I loans
     * via an Ornstein-Uhlenbeck continuous adjustment process driven by wholesale credit spreads and the output gap:
     *   Target = baseline + creditSens * excessCreditSpread - gapSens * outputGap
     *
     * @param float $currentSloos        Current net tightening percentage.
     * @param float $outputGap           Current output gap.
     * @param float $excessCreditSpread  Corporate credit spread above baseline.
     * @param float $dt                  Time increment in years.
     * @param float $dW                  Standard normal random shock.
     * @param float $kappa               Speed of adjustment toward target standards.
     * @param float $creditSensitivity   Sensitivity to corporate credit spread widening.
     * @param float $gapSensitivity      Sensitivity to economic contraction.
     * @param float $sigma               Diffusion volatility of bank underwriting standards.
     * @return float Updated net tightening fraction clamped between -40% (easing) and +85% (severe credit crunch).
     */
    public function calculateSloosCreditStandards(
        float $currentSloos,
        float $outputGap,
        float $excessCreditSpread,
        float $dt,
        float $dW,
        float $kappa = 1.80,
        float $creditSensitivity = 15.0,
        float $gapSensitivity = 3.0,
        float $sigma = 0.08
    ): float {
        $targetSloos = ($creditSensitivity * $excessCreditSpread) - ($gapSensitivity * $outputGap);
        $drift = $kappa * ($targetSloos - $currentSloos) * $dt;
        $diffusion = $sigma * sqrt($dt) * $dW;
        $newSloos = $currentSloos + $drift + $diffusion;

        return max(-0.40, min(0.85, $newSloos));
    }

    /**
     * Models the 3:2:1 Refining Crack Spread Index (Bourgeon et al. 1998, U.S. EIA).
     *
     * Evaluates gross refining margin per barrel ($/bbl) for refined products over crude oil feedstocks
     * using Schwartz (1997) mean-reverting dynamics driven by demand cycles and physical inventory tightness:
     *   Target = baseline * (1 + gapSens * outputGap) + convenienceAddOn
     *
     * @param float $currentCrack          Current crack spread in $/bbl.
     * @param float $outputGap             Current macroeconomic output gap.
     * @param float $energyInventoryIndex  Physical energy buffer inventory index.
     * @param float $dt                    Time increment in years.
     * @param float $dW                    Standard normal random shock.
     * @param float $baselineCrack         Neutral long-run crack spread (~$22/bbl).
     * @param float $kappa                 Speed of mean reversion.
     * @param float $sigma                 Volatility of crack margins.
     * @return float Updated refining crack spread in $/bbl clamped between $4.00 and $80.00.
     */
    public function calculateRefiningCrackSpreadStep(
        float $currentCrack,
        float $outputGap,
        float $energyInventoryIndex,
        float $dt,
        float $dW,
        float $baselineCrack = 22.0,
        float $kappa = 1.50,
        float $sigma = 0.25
    ): float {
        $demandFactor = 1.0 + (1.20 * $outputGap);
        $inventoryTightness = max(0.0, (100.0 - $energyInventoryIndex) / 100.0) * 15.0;
        $targetCrack = ($baselineCrack * max(0.30, $demandFactor)) + $inventoryTightness;

        $drift = $kappa * ($targetCrack - $currentCrack) * $dt;
        $diffusion = $sigma * $currentCrack * sqrt($dt) * $dW;
        $newCrack = $currentCrack + $drift + $diffusion;

        return max(4.0, min(80.0, $newCrack));
    }

    /**
     * Calculates the NY Fed Global Supply Chain Pressure Index (GSCPI) (Benigno et al. 2022).
     *
     * Constructs a normalized composite Z-score measuring cross-border logistics friction,
     * combining container freight rates, inventory stock gaps, and raw material price pressures:
     *   GSCPI = wFreight * ((Freight - Base) / sigmaFreight) + wInv * (InventoryGap / sigmaInv) + wMetals * ((Metals - Base) / sigmaMetals)
     *
     * @param float $freightRateIndex       Ocean freight index.
     * @param float $inventoryStockGap      Metzler inventory cycle gap.
     * @param float $industrialMetalsIndex  Industrial metals price index.
     * @param float $freightBase            Neutral freight baseline (100.0).
     * @param float $metalsBase             Neutral metals baseline (100.0).
     * @return float Normalized GSCPI Z-score clamped between -2.0 and +4.0.
     */
    public function calculateGscpiComposite(
        float $freightRateIndex,
        float $inventoryStockGap,
        float $industrialMetalsIndex,
        float $freightBase = 100.0,
        float $metalsBase = 100.0
    ): float {
        $freightZ = ($freightRateIndex - $freightBase) / 25.0;
        $inventoryZ = -$inventoryStockGap / 0.05; // Inventory shortages create supply chain stress
        $metalsZ = ($industrialMetalsIndex - $metalsBase) / 25.0;

        $composite = (0.50 * $freightZ) + (0.30 * $inventoryZ) + (0.20 * $metalsZ);
        return max(-2.0, min(4.0, $composite));
    }

    /**
     * Models the Capital Markets & M&A Deal Flow Index (Jovanovic & Rousseau 2002).
     *
     * Simulates global investment banking, private equity LBO, and IPO advisory volume
     * as an exponential function of valuation liquidity (ERP compression, tight high-yield spreads, and low volatility):
     *   Target = 100 * exp(-betaErp * erpExcess - betaHy * hySpreadExcess - betaVol * volExcess)
     *
     * @param float $currentDealIndex   Current deal flow index.
     * @param float $equityRiskPremium  Current equity risk premium.
     * @param float $hyCreditSpread     Current speculative high-yield credit spread.
     * @param float $marketVolatility   Current equity market volatility.
     * @param float $dt                 Time increment in years.
     * @param float $dW                 Standard normal random shock.
     * @param float $kappa              Speed of adjustment toward fundamental deal capacity.
     * @param float $sigma              Stochastic deal volatility.
     * @return float Updated deal activity index clamped between 20.0 and 250.0.
     */
    public function calculateCapitalMarketsDealIndexStep(
        float $currentDealIndex,
        float $equityRiskPremium,
        float $hyCreditSpread,
        float $marketVolatility,
        float $dt,
        float $dW,
        float $kappa = 1.60,
        float $sigma = 0.15
    ): float {
        $erpExcess = ($equityRiskPremium - 0.045) / 0.015;
        $hyExcess = ($hyCreditSpread - 0.048) / 0.020;
        $volExcess = ($marketVolatility - 0.15) / 0.06;

        $stressExponent = - (0.35 * $erpExcess + 0.45 * $hyExcess + 0.20 * $volExcess);
        $targetIndex = 100.0 * exp(max(-2.0, min(1.5, $stressExponent)));

        $drift = $kappa * ($targetIndex - $currentDealIndex) * $dt;
        $diffusion = $sigma * $currentDealIndex * sqrt($dt) * $dW;
        $newIndex = $currentDealIndex + $drift + $diffusion;

        return max(20.0, min(250.0, $newIndex));
    }

    /**
     * Calculates a standard diffusion index (e.g. ISM Purchasing Managers' Index) centered around a neutral baseline.
     *
     * In standard macroeconomic surveys (ISM, S&P Global), values above 50 indicate expansion while below 50 indicate contraction.
     *
     * @param float $baseline Neutral survey baseline (canonical 50.0).
     * @param array<int, array{deviation: float, sensitivity: float}> $drivers Component factors with their respective sensitivities.
     * @param float $min      Asymptotic floor.
     * @param float $max      Asymptotic ceiling.
     * @return float Calculated diffusion index score.
     */
    public function calculateDiffusionIndex(
        float $baseline,
        array $drivers,
        float $min = 30.0,
        float $max = 70.0
    ): float {
        $netAdjustment = 0.0;
        foreach ($drivers as $driver) {
            $netAdjustment += $driver['deviation'] * $driver['sensitivity'];
        }

        return max($min, min($max, $baseline + $netAdjustment));
    }

    /**
     * Stage-of-Processing Producer Price Index (PPI) wholesale pipeline inflation (Clark 1995).
     *
     * Evaluates intermediate wholesale inflation as a cost-push transmission of raw commodity inputs
     * (energy, metals, agriculture), freight/logistics bottlenecks (GSCPI), Unit Labor Costs (ULC),
     * and aggregate cyclical output gap demand pressure.
     *
     * @param float $metalsInflation   Annualized industrial metals price inflation.
     * @param float $energyInflation   Annualized energy price inflation.
     * @param float $agriInflation     Annualized agricultural commodity price inflation.
     * @param float $gscpiZ            Global supply chain pressure index (Z-score).
     * @param float $unitLaborCost     Unit labor cost growth (Wage Growth - TFP Trend Growth).
     * @param float $outputGap         Macroeconomic cyclical output gap.
     * @param array{metals: float, energy: float, agri: float, gscpi: float, ulc: float, demand: float} $weights Parameter weights.
     * @param float $min               Minimum annual PPI rate.
     * @param float $max               Maximum annual PPI rate.
     * @return float Producer price index inflation rate.
     */
    public function calculateStageOfProcessingPpi(
        float $metalsInflation,
        float $energyInflation,
        float $agriInflation,
        float $gscpiZ,
        float $unitLaborCost,
        float $outputGap,
        array $weights,
        float $min = -0.06,
        float $max = 0.25
    ): float {
        $commodityComponent = ($weights['metals'] * $metalsInflation)
            + ($weights['energy'] * $energyInflation)
            + ($weights['agri'] * $agriInflation);

        $supplyChainComponent = $weights['gscpi'] * $gscpiZ;
        $laborComponent = $weights['ulc'] * $unitLaborCost;
        $demandComponent = $weights['demand'] * $outputGap;

        $ppi = $commodityComponent + $supplyChainComponent + $laborComponent + $demandComponent;
        return max($min, min($max, $ppi));
    }

    /**
     * Poterba (1984) / Topel & Rosen (1988) Tobin's Q Housing Investment Dynamics.
     *
     * Models residential construction volume (Housing Starts) driven by the ratio of asset market home prices
     * to physical replacement costs, discounted by mortgage user costs and bank lending standards:
     *   q = P_residential / Cost_replacement
     *
     * @param float $currentStarts        Current housing starts index.
     * @param float $residentialPriceRatio Current home price relative to neutral baseline.
     * @param float $replacementCostRatio Current construction replacement cost relative to baseline.
     * @param float $userCost             User cost of residential capital (mortgage rate + taxes - inflation).
     * @param float $neutralUserCost      Structural equilibrium user cost of housing.
     * @param float $sloosTightening      SLOOS bank mortgage credit tightening percentage.
     * @param float $dt                   Time step in years.
     * @param float $dW                   Standard normal random shock.
     * @param array{baseline: float, qSens: float, costSens: float, sloosSens: float, kappa: float, sigma: float, min: float, max: float} $params Calibration parameters.
     * @return float Updated housing starts index.
     */
    public function calculateTobinsQHousingStarts(
        float $currentStarts,
        float $residentialPriceRatio,
        float $replacementCostRatio,
        float $userCost,
        float $neutralUserCost,
        float $sloosTightening,
        float $dt,
        float $dW,
        array $params
    ): float {
        $effectiveCost = max(0.20, $replacementCostRatio);
        $tobinsQ = $residentialPriceRatio / $effectiveCost;
        $qExcess = $tobinsQ - 1.0;

        $userCostExcess = $userCost - $neutralUserCost;
        $creditDrag = max(0.0, $sloosTightening);

        $targetStarts = $params['baseline']
            + ($params['qSens'] * $qExcess)
            - ($params['costSens'] * $userCostExcess)
            - ($params['sloosSens'] * $creditDrag);

        $clampedTarget = max($params['min'], min($params['max'], $targetStarts));

        $drift = $params['kappa'] * ($clampedTarget - $currentStarts) * $dt;
        $diffusion = $params['sigma'] * $currentStarts * sqrt($dt) * $dW;
        $newStarts = $currentStarts + $drift + $diffusion;

        return max($params['min'], min($params['max'], $newStarts));
    }

    /**
     * Brunner-Meltzer / Friedman-Schwartz M2 Broad Money Supply & Credit Channel Dynamics.
     *
     * Derives annual M2 broad money supply growth from central bank balance sheet liquidity creation (QE/QT),
     * commercial banking credit multipliers (SLOOS underwriting standards), and output gap credit demand:
     *   Target = BaseGrowth + betaQE * BalanceSheet - betaSLOOS * SLOOS + betaY * OutputGap
     *
     * @param float $currentM2Growth  Current annual M2 money supply growth rate.
     * @param float $baseGrowth       Long-run neutral M2 growth matching potential output and inflation target.
     * @param float $balanceSheetIntensity Central bank balance sheet intensity (+ for QE, - for QT).
     * @param float $sloosTightening  Net percentage of banks tightening credit standards.
     * @param float $outputGap        Cyclical GDP output gap.
     * @param float $dt               Time step in years.
     * @param float $dW               Standard normal random shock.
     * @param array{qeSens: float, sloosSens: float, gapSens: float, kappa: float, sigma: float, min: float, max: float} $params Calibration parameters.
     * @return float Updated annual M2 money supply growth rate.
     */
    public function calculateBroadMoneyGrowth(
        float $currentM2Growth,
        float $baseGrowth,
        float $balanceSheetIntensity,
        float $sloosTightening,
        float $outputGap,
        float $dt,
        float $dW,
        array $params
    ): float {
        $targetM2Growth = $baseGrowth
            + ($params['qeSens'] * $balanceSheetIntensity)
            - ($params['sloosSens'] * max(0.0, $sloosTightening))
            + ($params['gapSens'] * $outputGap);

        $clampedTarget = max($params['min'], min($params['max'], $targetM2Growth));

        $drift = $params['kappa'] * ($clampedTarget - $currentM2Growth) * $dt;
        $diffusion = $params['sigma'] * sqrt($dt) * $dW;
        $newGrowth = $currentM2Growth + $drift + $diffusion;

        return max($params['min'], min($params['max'], $newGrowth));
    }

    /**
     * Calculates a capacity-constrained counter-cyclical revenue expansion multiplier for distressed debt funds.
     *
     * In empirical corporate finance and distressed debt workouts (Acharya, Shin, & Yorulmazer 2011; Oaktree Capital),
     * asset recovery opportunities surge during credit crises but are bounded by total market inventory and
     * market impact friction. This is modeled via a Michaelis-Menten / Hill capacity saturation function:
     * ΔM = M_max * (S / (S + K_s)).
     *
     * @param float $rawDistressSignal Aggregate credit spread, default rate, and output gap distress intensity signal.
     * @param float $maxMultiplier     Maximum asymptotic revenue expansion multiplier (e.g. 1.25 = +125%).
     * @param float $halfSaturation    Distress intensity signal at which half of the maximum surge is realized.
     * @return float Diminishing counter-cyclical revenue expansion multiplier in [0, maxMultiplier].
     */
    public function calculateDiminishingDistressMultiplier(
        float $rawDistressSignal,
        float $maxMultiplier = 1.25,
        float $halfSaturation = 1.0
    ): float {
        if ($rawDistressSignal <= 0.0) {
            return 0.0;
        }

        $ks = max(0.001, $halfSaturation);
        return $maxMultiplier * ($rawDistressSignal / ($rawDistressSignal + $ks));
    }

    /**
     * Calculates cyclical demand shift from manufacturing diffusion survey indices (ISM / S&P PMI).
     *
     * In empirical macroeconomics, a diffusion index above 50 indicates expansion while below 50 indicates contraction.
     * Normalized as percentage deviation from neutral baseline (50.0).
     *
     * @param float $pmi         Manufacturing purchasing managers' index.
     * @param float $baseline    Neutral survey baseline (canonical 50.0).
     * @param float $sensitivity Sector demand sensitivity multiplier.
     * @return float Cyclical demand shift bounded in [-0.30, 0.30].
     */
    public static function calculatePmiDemandShift(
        float $pmi,
        float $baseline = MacroEngine::PMI_BASELINE,
        float $sensitivity = 0.50
    ): float {
        $base = max(1.0, $baseline);
        $deviation = ($pmi - $base) / $base;
        return max(-0.30, min(0.30, $deviation * $sensitivity));
    }

    /**
     * Stage-of-Processing Producer Price Index (PPI) variable cost drag (Clark 1995).
     *
     * Evaluates wholesale input material cost pressure on gross variable margins,
     * mitigated by the firm's structural pricing power.
     *
     * @param float $ppi             Producer price wholesale inflation rate.
     * @param float $targetInflation Central bank target inflation benchmark (~2%).
     * @param float $pricingPower    Firm pricing power index [0.0, 1.0].
     * @param float $sensitivity     Sector gross cost sensitivity multiplier.
     * @return float Margin cost penalty bounded in [0.0, 0.25].
     */
    public static function calculatePpiCostDrag(
        float $ppi,
        float $targetInflation = MacroEngine::TARGET_INFLATION,
        float $pricingPower = 0.50,
        float $sensitivity = 0.50
    ): float {
        $excessPpi = max(0.0, $ppi - $targetInflation);
        $effectivePassThrough = 1.0 - min(1.0, max(0.0, $pricingPower));
        return min(0.25, $excessPpi * $effectivePassThrough * $sensitivity);
    }

    /**
     * Calculates the mark-to-market revaluation of a credit portfolio under a spread move (first-order duration approximation).
     *
     * Standard fixed income sensitivity: \Delta P / P \approx -D_s * \Delta s, where D_s is the spread duration
     * of the book. Spreads gapping wider reprice held bonds and preferreds downward in the current period,
     * while spread compression books an unrealized gain. This is distinct from carry: the loss lands immediately,
     * the higher yield is only earned over subsequent periods.
     *
     * @param float $spreadChange   Change in credit spread over the period (positive = widening).
     * @param float $spreadDuration Spread duration of the credit book in years.
     * @return float Portfolio revaluation as a fraction of book value, bounded in [-0.40, 0.40].
     */
    public static function calculateCreditSpreadMarkToMarket(float $spreadChange, float $spreadDuration): float
    {
        $duration = max(0.0, $spreadDuration);
        return max(-0.40, min(0.40, -$spreadChange * $duration));
    }

    /**
     * Calculates construction and building material volume shifts from residential housing starts (Tobin's q).
     *
     * Normalized as percentage deviation from neutral housing starts baseline (100.0).
     *
     * @param float $starts      Residential housing starts index.
     * @param float $baseline    Neutral activity baseline (canonical 100.0).
     * @param float $sensitivity Sector volume sensitivity multiplier.
     * @return float Volume shift bounded in [-0.25, 0.25].
     */
    public static function calculateHousingStartsShift(
        float $starts,
        float $baseline = MacroEngine::HOUSING_STARTS_BASELINE,
        float $sensitivity = 0.30
    ): float {
        $base = max(1.0, $baseline);
        $deviation = ($starts - $base) / $base;
        return max(-0.25, min(0.25, $deviation * $sensitivity));
    }

    /**
     * Calculates international merchandise trade flow volume shifts (Mundell-Fleming).
     *
     * Evaluates net exports as a fraction of GDP relative to baseline structural trade balance (-2.8%).
     *
     * @param float $tradeBalance Current trade balance to GDP ratio.
     * @param float $baseline     Neutral structural trade balance baseline (-0.028).
     * @param float $sensitivity  Trade volume elasticity multiplier.
     * @return float Trade volume shift bounded in [-0.20, 0.20].
     */
    public static function calculateTradeBalanceShift(
        float $tradeBalance,
        float $baseline = MacroEngine::TRADE_BALANCE_BASELINE,
        float $sensitivity = 2.0
    ): float {
        $deviation = $tradeBalance - $baseline;
        return max(-0.20, min(0.20, $deviation * $sensitivity));
    }

    /**
     * Calculates broad liquidity expansion/contraction shifts from M2 money supply growth (Friedman-Schwartz).
     *
     * Evaluates systemic financial liquidity driving deposit growth, AUM fund inflows, and retail market participation.
     *
     * @param float $m2Growth    Annual broad money supply M2 growth rate.
     * @param float $baseline    Neutral equilibrium M2 growth rate (~5.5%).
     * @param float $sensitivity Liquidity sensitivity multiplier.
     * @return float Liquidity shift bounded in [-0.15, 0.15].
     */
    public static function calculateBroadMoneyLiquidityShift(
        float $m2Growth,
        float $baseline = MacroEngine::M2_BASE_GROWTH,
        float $sensitivity = 0.50
    ): float {
        $deviation = $m2Growth - $baseline;
        return max(-0.15, min(0.15, $deviation * $sensitivity));
    }

    /**
     * Calculates factory and industrial throughput shifts from Federal Reserve G.17 capacity utilization.
     *
     * Normalized using percentage point deviations divided by 100 to prevent runaway scaling.
     *
     * @param float $cuRate      Industrial capacity utilization rate in percentage (e.g. 78.5).
     * @param float $baseline    Neutral capacity utilization baseline (~78.5%).
     * @param float $sensitivity Sector throughput sensitivity multiplier.
     * @return float Throughput shift bounded in [-0.15, 0.15].
     */
    public static function calculateCapacityUtilizationShift(
        float $cuRate,
        float $baseline = MacroEngine::CU_BASELINE,
        float $sensitivity = 0.40
    ): float {
        $deviation = ($cuRate - $baseline) / 100.0;
        return max(-0.15, min(0.15, $deviation * $sensitivity));
    }

    /**
     * Converts a single reporting period into a seasonally adjusted annual rate (SAAR).
     *
     * Standard BEA/BLS seasonal adjustment: the period value is divided by its seasonal
     * factor to recover the underlying run-rate, then scaled to an annual basis. Exact
     * when the seasonal factors are known a priori rather than estimated.
     *
     * @param float $periodValue    The single-period value (e.g., quarterly revenue).
     * @param float $seasonalFactor The period's empirical seasonal factor (e.g., 0.85).
     * @param int   $periodsPerYear The number of reporting periods per year (default 4 for quarterly).
     * @return float The seasonally adjusted annual rate (SAAR).
     */
    public static function calculateSeasonallyAdjustedAnnualRate(
        float $periodValue,
        float $seasonalFactor,
        int $periodsPerYear = 4
    ): float {
        return ($periodValue / max(0.01, $seasonalFactor)) * $periodsPerYear;
    }
}
